export type AppLanguage = 'ar' | 'en' | 'fr' | 'de' | 'es' | 'tr' | 'ur' | 'ru' | 'zh' | 'ja';

export interface LanguageInfo {
  code: AppLanguage;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'rtl' | 'ltr';
  speechLang: string;
  aiPromptLang: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    flag: '🇸🇦',
    dir: 'rtl',
    speechLang: 'ar-SA',
    aiPromptLang: 'Arabic (العربية)',
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇺🇸',
    dir: 'ltr',
    speechLang: 'en-US',
    aiPromptLang: 'English',
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    dir: 'ltr',
    speechLang: 'fr-FR',
    aiPromptLang: 'French (Français)',
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    dir: 'ltr',
    speechLang: 'de-DE',
    aiPromptLang: 'German (Deutsch)',
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    dir: 'ltr',
    speechLang: 'es-ES',
    aiPromptLang: 'Spanish (Español)',
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    dir: 'ltr',
    speechLang: 'tr-TR',
    aiPromptLang: 'Turkish (Türkçe)',
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    flag: '🇵🇰',
    dir: 'rtl',
    speechLang: 'ur-PK',
    aiPromptLang: 'Urdu (اردو)',
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    dir: 'ltr',
    speechLang: 'ru-RU',
    aiPromptLang: 'Russian (Русский)',
  },
  {
    code: 'zh',
    name: 'Chinese (Simplified)',
    nativeName: '中文 (简体)',
    flag: '🇨🇳',
    dir: 'ltr',
    speechLang: 'zh-CN',
    aiPromptLang: 'Chinese Simplified (中文)',
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    dir: 'ltr',
    speechLang: 'ja-JP',
    aiPromptLang: 'Japanese (日本語)',
  },
];

export function getLanguageInfo(code: AppLanguage): LanguageInfo {
  return SUPPORTED_LANGUAGES.find((l) => l.code === code) || SUPPORTED_LANGUAGES[0];
}

export interface TranslationSet {
  appName: string;
  settingsTitle: string;
  settingsSubtitle: string;
  apiKeyTitle: string;
  floatingBallTitle: string;
  backupTitle: string;
  appLockTitle: string;
  favoritesTitle: string;
  remindersTitle: string;
  archiveTitle: string;
  trashTitle: string;
  darkModeTitle: string;
  notificationsTitle: string;
  languagesTitle: string;
  rateTitle: string;
  contactTitle: string;
  homeTab: string;
  diariesTab: string;
  advisorTab: string;
  analyticsTab: string;
  settingsTab: string;
  apiKeySub: string;
  apiKeySubAuto: string;
  floatingBallSub: string;
  backupSub: string;
  appLockSub: string;
  favoritesSub: string;
  remindersSub: string;
  archiveSub: string;
  trashSub: string;
  darkModeSub: string;
  notificationsSub: string;
  languagesSub: string;
  rateSub: string;
  contactSub: string;
  selectLanguageTitle: string;
  selectLanguageSubtitle: string;
  confirmLanguage: string;
  welcomeModalTitle: string;
  welcomeModalDesc: string;

  // New Dashboard UI Strings
  notificationActiveNow: string;
  notificationHowAreYou: string;
  notificationTapShortcut: string;
  write: string;
  voiceRecord: string;
  mood: string;
  advisor: string;
  task: string;
  photo: string;
  greetingTitle: string;
  greetingDesc: string;
  fullCalendar: string;
  fullCalendarSub: string;
  directUploadTitle: string;
  attachPhoto: string;
  attachPhotoSub: string;
  freeWrite: string;
  freeWriteSub: string;
  audioFile: string;
  audioFileSub: string;
  phoneVideo: string;
  phoneVideoSub: string;
  aiAdvisor: string;
  aiAdvisorSub: string;
  bookDoc: string;
  bookDocSub: string;
  streakTitle: string;
  dayStreak: string;
  streakEncouragement: string;
  longestStreak: string;
  recentWeek: string;
  selectDateTitle: string;
  quoteTitle: string;
  aiInspirationBtn: string;
  dhikrTitle: string;
  dhikrSub: string;
  dhikrCounterBtn: string;
  dhikrCountLabel: string;
  dhikrFooter: string;
  moodScaleTitle: string;
  moodScaleDesc: string;
  moodRating: string;
  waterTrackerTitle: string;
  waterTrackerDesc: string;
  waterConsumed: string;
  waterRemaining: string;
  symptomsTitle: string;
  symptomsDesc: string;
  symptomRapidHeart: string;
  symptomHeadache: string;
  symptomShortnessBreath: string;
  symptomBackTension: string;
  symptomFatigue: string;
  symptomPoorSleep: string;
  symptomStomach: string;
  symptomTremors: string;
  breathingTitle: string;
  breathingDesc: string;
  startBreathingBtn: string;
  selfCareTitle: string;
  sleepHours: string;
  workoutMinutes: string;
  medicationDose: string;
  habitTitle: string;
  habitSub: string;
  addHabitBtn: string;
  reportTitle: string;
  reportDesc: string;
  generateReportBtn: string;
  lifeMapTitle: string;
  lifeMapSub: string;
  balanceIndex: string;
  excellentBalance: string;
  sleepQuality: string;
  exerciseActivity: string;
  medicationCompliance: string;
  subHabits: string;
  timelineTitle: string;
  tipTitle: string;
  tipText: string;
}

export const MULTI_TRANSLATIONS: Record<AppLanguage, TranslationSet> = {
  ar: {
    appName: "حياة AI",
    settingsTitle: "الإعدادات العامة",
    settingsSubtitle: "تخصيص مساعد الذكي، قفل الحماية، وتزامن بياناتك",
    apiKeyTitle: "مفتاح API الخاص بك 🔑",
    floatingBallTitle: "عرض الكرة العائمة 🔘",
    backupTitle: "النسخ الاحتياطي والمزامنة ☁️",
    appLockTitle: "قفل التطبيق 🔐",
    favoritesTitle: "الملاحظات المفضلة ⭐",
    remindersTitle: "التذكيرات والمنبهات ⏰",
    archiveTitle: "أرشيف اليوميات 📥",
    trashTitle: "سلة المهملات 🗑️",
    darkModeTitle: "الوضع الداكن ☀️/🌙",
    notificationsTitle: "الإشعارات 🔔",
    languagesTitle: "لغات التطبيق 🌐",
    rateTitle: "قيمنا 👍",
    contactTitle: "تواصل مع مالك التطبيق للاقتراح والتطوير ✉️",
    homeTab: "الرئيسية",
    diariesTab: "اليوميات",
    advisorTab: "المستشار",
    analyticsTab: "التقدم والبيانات",
    settingsTab: "الإعدادات",
    apiKeySub: "حالة المفتاح: مخصّص ونشط محلياً 🟢",
    apiKeySubAuto: "حالة المفتاح: يتم التوفير سحابياً تلقائياً وبأمان ☁️",
    floatingBallSub: "تسهيل التنقل والتحكم السريع بالمساعد الذكي في أي وقت",
    backupSub: "حفظ ومزامنة مذكراتك سحابياً ومحلياً لمنع فقدان البيانات",
    appLockSub: "تأمين مذكراتك برمز مرور PIN مكوّن من 4 أرقام عند بدء التشغيل",
    favoritesSub: "تصفح والوصول السريع للمذكرات الأكثر أهمية (ذات 4 نجوم فما فوق)",
    remindersSub: "إدارة منبهات المهام المجدولة واليوميات",
    archiveSub: "استعراض مذكراتك المؤرشفة والقديمة",
    trashSub: "استعادة مذكراتك المحذوفة مؤخراً أو تصفيتها",
    darkModeSub: "تفعيل مظهر الوضع الليلي لحماية عينيك",
    notificationsSub: "تلقي تنبيهات دورية للعادات والتذكيرات اليومية",
    languagesSub: "تغيير لغة واجهة مستخدم التطبيق",
    rateSub: "ساعدنا على مواصلة تحسين التطبيق لرأيك الغالي",
    contactSub: "راسلنا باقتراحاتك وملاحظاتك القيمة لتطوير التطبيق",
    selectLanguageTitle: "اختر لغتك المفضلة 🌐",
    selectLanguageSubtitle: "اختر لغة الواجهة والذكاء الاصطناعي المفضلة لديك للبدء",
    confirmLanguage: "متابعة بهذه اللغة 🚀",
    welcomeModalTitle: "مرحباً بك في حياة AI 👋",
    welcomeModalDesc: "يرجى اختيار لغتك المفضلة لاستخدام التطبيق والمساعد الذكي والتحويل الصوتي بها بكفاءة كاملة.",

    notificationActiveNow: "حياة AI • نشط الآن 📱",
    notificationHowAreYou: "كيف تشعر الآن يا صديقي؟ 😊",
    notificationTapShortcut: "اضغط على أي من الاختصارات السريعة أدناه لتدوين مذكراتك أو رصد حالتك المزاجية مباشرة.",
    write: "كتابة",
    voiceRecord: "تسجيل",
    mood: "مزاجي",
    advisor: "مستشار",
    task: "مهمة",
    photo: "صورة",
    greetingTitle: "أهلاً بك وطاب يومك يا صديقي النبيل ☕",
    greetingDesc: "اليوم هو يوم جديد للنمو والتصالح مع الذات. تذكر أن تدوين أفكارك البسيطة اليوم يمنحك أفضل نصائح وتوصيات سلوكية غداً.",
    fullCalendar: "التقويم الكامل واستعراض الأيام 📅",
    fullCalendarSub: "يومياتي، كتب، أنشطة، اضغط لتصفح كل ما حدث في أي يوم (AI واستشارات)",
    directUploadTitle: "الوصول المباشر لملفات الهاتف ومرفقات اليومية ⚡",
    attachPhoto: "إرفاق صورة",
    attachPhotoSub: "من ألبوم الهاتف",
    freeWrite: "كتابة حرة",
    freeWriteSub: "فتح محرر فارغ",
    audioFile: "ملف صوتي",
    audioFileSub: "تسجيل أو ملف ريكورد",
    phoneVideo: "فيديو الهاتف",
    phoneVideoSub: "تحميل مقطع مرئي",
    aiAdvisor: "AI مستشار",
    aiAdvisorSub: "تحليل وتوصيات فورية",
    bookDoc: "كتاب أو وثيقة",
    bookDocSub: "أو نص PDF تحميل",
    streakTitle: "سلسلة الالتزام والتدوين",
    dayStreak: "يوم متتالي",
    streakEncouragement: "رائع! لقد دونت أفكارك اليوم وحافظت على توهجك ✨",
    longestStreak: "أطول سلسلة تاريخية",
    recentWeek: "متابعة الأسبوع الأخير",
    selectDateTitle: "إختر اليوم لتسجيل أو عرض الأنشطة:",
    quoteTitle: "حكمة اليوم لراحة البال والتحفيز النفسي 🌿",
    aiInspirationBtn: "(AI) إلهام ذكي 🪄",
    dhikrTitle: "روضة الأذكار والإيمانيات 🌿",
    dhikrSub: "( سبحان الله، الحمد لله، لا إله إلا الله، الله أكبر ) ❤️ صلِّ على سيدك النبي ❤️",
    dhikrCounterBtn: "اضغط هنا للتسبيح والصلاة على النبي 🪙",
    dhikrCountLabel: "العداد:",
    dhikrFooter: "يحتفظ العداد بتسبيحاتك دائماً حتى عند إغلاق أو فتح الموقع",
    moodScaleTitle: "مقياس المزاج الرقمي السريع (1 - 10) 😐",
    moodScaleDesc: "اسحب المؤشر لتوثيق حالتك المزاجية الحالية في ثانية واحدة؛ يدعم الذكاء الاصطناعي التقييم كمدخل يومي سريع.",
    moodRating: "تقييم المزاج:",
    waterTrackerTitle: "عداد كؤوس الماء التفاعلي اليومي 💧",
    waterTrackerDesc: "اضغط على الكؤوس أدناه لتسجيل كميات المياه المستهلكة؛ شرب المياه يحمي جهازك العصبي من التوتر.",
    waterConsumed: "الكمية المستهلكة:",
    waterRemaining: "تبقى لك بعض الكؤوس للوصول للمعدل المثالي 💡",
    symptomsTitle: "الأعراض الجسدية المصاحبة لقلق اليوم ⚡",
    symptomsDesc: "حدد أي من الأعراض الفسيولوجية التالية شعرت بها اليوم لتساعد الذكاء الاصطناعي في رصد الروابط النفس-جسدية.",
    symptomRapidHeart: "تسرع نبضات القلب 💓",
    symptomHeadache: "صداع وضغط رأس 🤯",
    symptomShortnessBreath: "ضيق وصعوبة تنفس 🫁",
    symptomBackTension: "شد عضلي وآلام ظهر 🧘",
    symptomFatigue: "خمول وإرهاق عام 🔋",
    symptomPoorSleep: "أرق وقلة جودة النوم 😴",
    symptomStomach: "اضطراب وتوتر معدة 🤢",
    symptomTremors: "تعرق زائد ورجفة أطراف 🥶",
    breathingTitle: "مساعد التنفس الصندوقي الاسترخائي 🧘‍♂️",
    breathingDesc: "طريقة تنفس مثبتة علمياً لتهدئة ضربات القلب وتحفيز السلام العصبي فوراً (4 ثوان لكل مرحلة)",
    startBreathingBtn: "بدء تمرين التنفس ▶️",
    selfCareTitle: "أهداف الرعاية الذاتية والصحة النفسية 📝",
    sleepHours: "ساعات النوم 🌙",
    workoutMinutes: "التمارين الرياضية 🏃",
    medicationDose: "جرعة العلاج/الفيتامينات 💊",
    habitTitle: "تتبع العادات السلوكية والروتين 🎯",
    habitSub: "اختر يوماً من التقويم ثم حدد العادات المنجزة لتسجيل الالتزام ودعم تحليلك السلوكي اليومي.",
    addHabitBtn: "إضافة عادة +",
    reportTitle: "التقييم السلوكي وتقارير العادات الذكية (AI) 📊",
    reportDesc: "حدد الفترة الزمنية المطلوبة ليقوم الذكاء الاصطناعي بدراسة اتجاهاتك السلوكية تقديم توصيات عملية لتعزيز صحتك النفسية.",
    generateReportBtn: "توليد تقرير التقييم السلوكي بالذكاء الاصطناعي 🧠",
    lifeMapTitle: "خريطة ومؤشرات الحياة اليومية 📊",
    lifeMapSub: "لوحة تحكم تحليلية متكاملة لربط الأنشطة السلوكية بجودة صحتك النفسية",
    balanceIndex: "مؤشر التوازن والصحة اليومي:",
    excellentBalance: "توازن ممتاز",
    sleepQuality: "جودة النوم 🌙",
    exerciseActivity: "الحركة والرياضة 🏃",
    medicationCompliance: "الالتزام بالأدوية 💊",
    subHabits: "إكمال العادات 🎯",
    timelineTitle: "شريط الزمن المتكامل وخطوات اليوم:",
    tipTitle: "نصيحة اليوم للصحة النفسية 💡",
    tipText: "عندما تشعر بضغط الامتحانات أو القلق، خذ دقيقة واحدة لممارسة تنفس الصندوق (شهيق 4 ثوان، كتم 4 ثوان، زفير 4 ثوان، كتم 4 ثوان)؛ فهذا ينشط العصب الحائر ويهدئ الجهاز العصبي فوراً.",
  },
  en: {
    appName: "Hayat AI",
    settingsTitle: "General Settings",
    settingsSubtitle: "Customize your smart assistant, privacy lock, and sync your data",
    apiKeyTitle: "Your API Key 🔑",
    floatingBallTitle: "Display Floating Ball 🔘",
    backupTitle: "Backup & Sync ☁️",
    appLockTitle: "App Lock 🔐",
    favoritesTitle: "Favorite Notes ⭐",
    remindersTitle: "Reminders & Alarms ⏰",
    archiveTitle: "Diary Archive 📥",
    trashTitle: "Trash Can 🗑️",
    darkModeTitle: "Dark Mode ☀️/🌙",
    notificationsTitle: "Notifications 🔔",
    languagesTitle: "App Languages 🌐",
    rateTitle: "Rate Us 👍",
    contactTitle: "Contact App Owner ✉️",
    homeTab: "Home",
    diariesTab: "Diaries",
    advisorTab: "Advisor",
    analyticsTab: "Analytics",
    settingsTab: "Settings",
    apiKeySub: "Key status: Customized & active locally 🟢",
    apiKeySubAuto: "Key status: Provided securely via cloud automatically ☁️",
    floatingBallSub: "Quick navigation and shortcut controls for your AI assistant",
    backupSub: "Sync and backup your diaries locally & to cloud securely",
    appLockSub: "Secure your notes with a 4-digit PIN lock on launch",
    favoritesSub: "Browse and quickly access your most important diaries (4+ stars)",
    remindersSub: "Manage scheduled task alarms and diary reminders",
    archiveSub: "Browse archived and older diary notes",
    trashSub: "Restore recently deleted diaries or filter them",
    darkModeSub: "Enable dark mode appearance to protect your eyes",
    notificationsSub: "Receive periodic alerts for habits and daily reminders",
    languagesSub: "Change the application user interface language",
    rateSub: "Help us continue improving the application with your feedback",
    contactSub: "Send us your valuable suggestions and notes to develop the app",
    selectLanguageTitle: "Choose Your Language 🌐",
    selectLanguageSubtitle: "Select your preferred language for the UI, voice recognition, and AI assistant",
    confirmLanguage: "Continue in this language 🚀",
    welcomeModalTitle: "Welcome to Hayat AI 👋",
    welcomeModalDesc: "Please select your preferred language to customize the app, voice recognition, and AI assistant.",

    notificationActiveNow: "Hayat AI • Active Now 📱",
    notificationHowAreYou: "How are you feeling right now, my friend? 😊",
    notificationTapShortcut: "Tap any shortcut below to log your notes or track your mood instantly.",
    write: "Write",
    voiceRecord: "Voice",
    mood: "Mood",
    advisor: "Advisor",
    task: "Task",
    photo: "Photo",
    greetingTitle: "Welcome and good day, noble friend ☕",
    greetingDesc: "Today is a new day for growth and self-harmony. Remember that logging simple thoughts today provides the best insights tomorrow.",
    fullCalendar: "Full Calendar & Day View 📅",
    fullCalendarSub: "Diaries, books, activities - click to explore everything logged on any day (AI & Consultation)",
    directUploadTitle: "Direct File Access & Diary Attachments ⚡",
    attachPhoto: "Attach Photo",
    attachPhotoSub: "From device gallery",
    freeWrite: "Free Writing",
    freeWriteSub: "Open blank editor",
    audioFile: "Audio File",
    audioFileSub: "Record or voice file",
    phoneVideo: "Device Video",
    phoneVideoSub: "Upload video clip",
    aiAdvisor: "AI Advisor",
    aiAdvisorSub: "Instant analysis & tips",
    bookDoc: "Book / Document",
    bookDocSub: "Upload PDF or text",
    streakTitle: "Logging & Habit Streak",
    dayStreak: "Days Streak",
    streakEncouragement: "Great job! You logged your thoughts today and kept your momentum ✨",
    longestStreak: "Longest Streak History",
    recentWeek: "Recent Week Progress",
    selectDateTitle: "Select a date to log or view activities:",
    quoteTitle: "Daily Wisdom & Psychological Motivation 🌿",
    aiInspirationBtn: "(AI) Smart Inspiration 🪄",
    dhikrTitle: "Daily Mindful & Spiritual Reflection 🌿",
    dhikrSub: "Take a moment for quiet reflection, gratitude, and peace ❤️",
    dhikrCounterBtn: "Tap here for counter & mindful reflection 🪙",
    dhikrCountLabel: "Counter:",
    dhikrFooter: "Your count is saved permanently across app sessions.",
    moodScaleTitle: "Quick Digital Mood Tracker (1 - 10) 😐",
    moodScaleDesc: "Drag the slider to record your mood in one second; AI will incorporate this into your daily mental health assessment.",
    moodRating: "Mood Rating:",
    waterTrackerTitle: "Daily Interactive Water Cups Tracker 💧",
    waterTrackerDesc: "Tap the cups below to record water consumed. Staying hydrated calms your nervous system.",
    waterConsumed: "Consumed Amount:",
    waterRemaining: "A few cups left to reach your optimal daily goal 💡",
    symptomsTitle: "Physical Symptoms Tracker ⚡",
    symptomsDesc: "Check any physiological symptoms experienced today to help AI analyze mind-body connections.",
    symptomRapidHeart: "Rapid Heartbeat 💓",
    symptomHeadache: "Headache / Pressure 🤯",
    symptomShortnessBreath: "Shortness of Breath 🫁",
    symptomBackTension: "Muscle & Back Tension 🧘",
    symptomFatigue: "General Fatigue 🔋",
    symptomPoorSleep: "Insomnia / Poor Sleep 😴",
    symptomStomach: "Stomach Distress 🤢",
    symptomTremors: "Excessive Sweating / Tremors 🥶",
    breathingTitle: "Box Breathing Relaxation Assistant 🧘‍♂️",
    breathingDesc: "Scientifically proven technique to slow heart rate and activate nerve calm (4 seconds per phase)",
    startBreathingBtn: "Start Breathing Exercise ▶️",
    selfCareTitle: "Self-Care & Mental Health Goals 📝",
    sleepHours: "Sleep Hours 🌙",
    workoutMinutes: "Exercise / Workout 🏃",
    medicationDose: "Medication / Vitamins 💊",
    habitTitle: "Behavioral Habit & Routine Tracker 🎯",
    habitSub: "Select a date and check off completed habits to boost consistency and AI insights.",
    addHabitBtn: "Add Habit +",
    reportTitle: "Behavioral Evaluation & AI Habit Reports 📊",
    reportDesc: "Select a timeframe to generate an AI evaluation of your behavioral trends and wellness advice.",
    generateReportBtn: "Generate AI Behavioral Report 🧠",
    lifeMapTitle: "Daily Life Map & Wellness Indicators 📊",
    lifeMapSub: "Comprehensive analytics connecting habits directly to overall mental health quality.",
    balanceIndex: "Daily Health & Balance Index:",
    excellentBalance: "Excellent Balance",
    sleepQuality: "Sleep Quality 🌙",
    exerciseActivity: "Exercise & Activity 🏃",
    medicationCompliance: "Medication Compliance 💊",
    subHabits: "Habit Completion 🎯",
    timelineTitle: "Integrated Timeline & Daily Steps:",
    tipTitle: "Daily Mental Health Tip 💡",
    tipText: "When feeling stressed or overwhelmed, practice 1 minute of Box Breathing (Inhale 4s, Hold 4s, Exhale 4s, Hold 4s) to calm your vagus nerve immediately.",
  },
  fr: {
    appName: "Hayat AI",
    settingsTitle: "Paramètres généraux",
    settingsSubtitle: "Personnalisez votre assistant intelligent, verrouillez vos données et synchronisez",
    apiKeyTitle: "Votre clé API 🔑",
    floatingBallTitle: "Bouton flottant 🔘",
    backupTitle: "Sauvegarde & Synchro ☁️",
    appLockTitle: "Verrouillage de l'application 🔐",
    favoritesTitle: "Notes favorites ⭐",
    remindersTitle: "Rappels & Alarmes ⏰",
    archiveTitle: "Archives des journaux 📥",
    trashTitle: "Corbeille 🗑️",
    darkModeTitle: "Mode Sombre ☀️/🌙",
    notificationsTitle: "Notifications 🔔",
    languagesTitle: "Langues de l'application 🌐",
    rateTitle: "Évaluez-nous 👍",
    contactTitle: "Contacter le propriétaire ✉️",
    homeTab: "Accueil",
    diariesTab: "Journaux",
    advisorTab: "Conseiller",
    analyticsTab: "Statistiques",
    settingsTab: "Paramètres",
    apiKeySub: "Statut clé: Personnalisée & active localement 🟢",
    apiKeySubAuto: "Statut clé: Fournie automatiquement par le cloud ☁️",
    floatingBallSub: "Accès rapide aux raccourcis de l'assistant IA",
    backupSub: "Sauvegardez vos journaux localement et sur le cloud",
    appLockSub: "Protégez vos notes avec un code PIN à 4 chiffres",
    favoritesSub: "Parcourez vos journaux les plus importants (4+ étoiles)",
    remindersSub: "Gérez les alarmes de tâches et rappels de journal",
    archiveSub: "Consultez vos anciens journaux archivés",
    trashSub: "Restaurez vos journaux supprimés récemment",
    darkModeSub: "Activez le mode sombre pour protéger vos yeux",
    notificationsSub: "Recevez des alertes régulières pour vos habitudes",
    languagesSub: "Changer la langue de l'interface utilisateur",
    rateSub: "Aidez-nous à améliorer l'application avec vos avis",
    contactSub: "Envoyez-nous vos suggestions pour faire évoluer l'app",
    selectLanguageTitle: "Choisissez votre langue 🌐",
    selectLanguageSubtitle: "Sélectionnez votre langue pour l'interface, la reconnaissance vocale et l'IA",
    confirmLanguage: "Continuer dans cette langue 🚀",
    welcomeModalTitle: "Bienvenue sur Hayat AI 👋",
    welcomeModalDesc: "Veuillez sélectionner votre langue préférée pour personnaliser l'application et l'assistant IA.",

    notificationActiveNow: "Hayat AI • Actif 📱",
    notificationHowAreYou: "Comment vous sentez-vous maintenant ? 😊",
    notificationTapShortcut: "Appuyez sur un raccourci ci-dessous pour noter vos pensées ou votre humeur.",
    write: "Écrire",
    voiceRecord: "Vocal",
    mood: "Humeur",
    advisor: "Conseiller",
    task: "Tâche",
    photo: "Photo",
    greetingTitle: "Bienvenue et bonne journée, mon cher ami ☕",
    greetingDesc: "Aujourd'hui est un nouveau jour pour grandir. Écrire vos pensées simples vous aide pour demain.",
    fullCalendar: "Calendrier complet & Vue quotidienne 📅",
    fullCalendarSub: "Journaux, livres, activités - cliquez pour explorer chaque jour",
    directUploadTitle: "Accès direct aux fichiers & pièces jointes ⚡",
    attachPhoto: "Joindre une photo",
    attachPhotoSub: "Depuis la galerie",
    freeWrite: "Écriture libre",
    freeWriteSub: "Ouvrir éditeur vide",
    audioFile: "Fichier audio",
    audioFileSub: "Enregistrement ou audio",
    phoneVideo: "Vidéo mobile",
    phoneVideoSub: "Téléverser une vidéo",
    aiAdvisor: "Conseiller IA",
    aiAdvisorSub: "Analyse & conseils instantanés",
    bookDoc: "Livre / Document",
    bookDocSub: "PDF ou texte",
    streakTitle: "Série d'assiduité",
    dayStreak: "Jours consécutifs",
    streakEncouragement: "Bravo ! Vous avez écrit aujourd'hui et entretenu votre élan ✨",
    longestStreak: "Meilleure série historique",
    recentWeek: "Suivi de la semaine",
    selectDateTitle: "Sélectionnez une date pour consulter ou saisir :",
    quoteTitle: "Sagesse quotidienne & Motivation 🌿",
    aiInspirationBtn: "(IA) Inspiration intelligente 🪄",
    dhikrTitle: "Méditation & Réflexion spirituelle 🌿",
    dhikrSub: "Prenez un moment pour la méditation, la gratitude et la paix intérieure ❤️",
    dhikrCounterBtn: "Appuyez ici pour compter et méditer 🪙",
    dhikrCountLabel: "Compteur :",
    dhikrFooter: "Votre score est conservé en permanence.",
    moodScaleTitle: "Suivi de l'humeur rapide (1 - 10) 😐",
    moodScaleDesc: "Glissez pour enregistrer votre humeur en 1 seconde pour votre bilan IA.",
    moodRating: "Évaluation humeur :",
    waterTrackerTitle: "Suivi quotidien des verres d'eau 💧",
    waterTrackerDesc: "Appuyez sur les verres pour enregistrer votre eau bu. S'hydrater apaise le système nerveux.",
    waterConsumed: "Quantité consommée :",
    waterRemaining: "Encore quelques verres pour atteindre l'objectif idéal 💡",
    symptomsTitle: "Suivi des symptômes physiques ⚡",
    symptomsDesc: "Cochez les symptômes physiques ressentis pour analyser l'interconnexion corps-esprit.",
    symptomRapidHeart: "Palpitations cardiaques 💓",
    symptomHeadache: "Maux de tête / Pression 🤯",
    symptomShortnessBreath: "Essoufflement 🫁",
    symptomBackTension: "Tensions musculaires 🧘",
    symptomFatigue: "Fatigue générale 🔋",
    symptomPoorSleep: "Insomnie / Mauvais sommeil 😴",
    symptomStomach: "Maux d'estomac 🤢",
    symptomTremors: "Seurs excessives / Tremblements 🥶",
    breathingTitle: "Assistant de respiration carrée 🧘‍♂️",
    breathingDesc: "Technique scientifiquement prouvée pour ralentir le rythme cardiaque (4 secondes par phase)",
    startBreathingBtn: "Démarrer l'exercice ▶️",
    selfCareTitle: "Objectifs de bien-être & santé mentale 📝",
    sleepHours: "Heures de sommeil 🌙",
    workoutMinutes: "Exercice physique 🏃",
    medicationDose: "Médicaments / Vitamines 💊",
    habitTitle: "Suivi des habitudes & routine 🎯",
    habitSub: "Sélectionnez une date et cochez vos habitudes réalisées.",
    addHabitBtn: "Ajouter une habitude +",
    reportTitle: "Évaluation comportementale IA 📊",
    reportDesc: "Choisissez une période pour générer un rapport comportemental IA.",
    generateReportBtn: "Générer le rapport IA 🧠",
    lifeMapTitle: "Carte de vie & Indicateurs de santé 📊",
    lifeMapSub: "Tableau de bord reliant habitudes et santé mentale.",
    balanceIndex: "Indice d'équilibre quotidien :",
    excellentBalance: "Excellent équilibre",
    sleepQuality: "Qualité du sommeil 🌙",
    exerciseActivity: "Activité physique 🏃",
    medicationCompliance: "Suivi traitement 💊",
    subHabits: "Habitudes complétées 🎯",
    timelineTitle: "Chronologie & Étapes du jour :",
    tipTitle: "Conseil santé mentale du jour 💡",
    tipText: "En cas de stress ou d'anxiété, pratiquez 1 minute de respiration en carré (Inspiration 4s, Maintien 4s, Expiration 4s, Maintien 4s) pour apaiser le système nerveux.",
  },
  de: {
    appName: "Hayat AI",
    settingsTitle: "Allgemeine Einstellungen",
    settingsSubtitle: "Passen Sie Ihren KI-Assistenten, PIN-Sperre und Synchronisierung an",
    apiKeyTitle: "Ihr API-Schlüssel 🔑",
    floatingBallTitle: "Schwebender Button 🔘",
    backupTitle: "Sicherung & Synchro ☁️",
    appLockTitle: "App-Sperre 🔐",
    favoritesTitle: "Favoriten ⭐",
    remindersTitle: "Erinnerungen & Alarme ⏰",
    archiveTitle: "Tagebuch-Archiv 📥",
    trashTitle: "Papierkorb 🗑️",
    darkModeTitle: "Dunkelmodus ☀️/🌙",
    notificationsTitle: "Benachrichtigungen 🔔",
    languagesTitle: "App-Sprachen 🌐",
    rateTitle: "Bewerten Sie uns 👍",
    contactTitle: "Entwickler kontaktieren ✉️",
    homeTab: "Startseite",
    diariesTab: "Tagebücher",
    advisorTab: "Berater",
    analyticsTab: "Analysen",
    settingsTab: "Einstellungen",
    apiKeySub: "Schlüsselstatus: Lokal aktiv 🟢",
    apiKeySubAuto: "Schlüsselstatus: Sicher über die Cloud bereitgestellt ☁️",
    floatingBallSub: "Schnellzugriff auf KI-Assistenten-Funktionen",
    backupSub: "Sichern Sie Ihre Tagebücher lokal und in der Cloud",
    appLockSub: "Sichern Sie Ihre Notizen mit einer 4-stelligen PIN",
    favoritesSub: "Durchsuchen Sie Ihre wichtigsten Tagebücher (4+ Sterne)",
    remindersSub: "Verwalten Sie Aufgabenerinnerungen und Wecker",
    archiveSub: "Durchsuchen Sie archivierte Einträge",
    trashSub: "Stellen Sie gelöschte Einträge wieder her",
    darkModeSub: "Aktivieren Sie den Dunkelmodus für Ihre Augen",
    notificationsSub: "Erhalten Sie regelmäßige Erinnerungen",
    languagesSub: "Ändern Sie die Sprache der Benutzeroberfläche",
    rateSub: "Helfen Sie uns, die App weiter zu verbessern",
    contactSub: "Senden Sie uns Ihre wertvollen Vorschläge",
    selectLanguageTitle: "Wählen Sie Ihre Sprache 🌐",
    selectLanguageSubtitle: "Wählen Sie Ihre bevorzugte Sprache für Benutzeroberfläche und KI-Assistenten",
    confirmLanguage: "In dieser Sprache fortfahren 🚀",
    welcomeModalTitle: "Willkommen bei Hayat AI 👋",
    welcomeModalDesc: "Bitte wählen Sie Ihre bevorzugte Sprache zur Personalisierung der App.",

    notificationActiveNow: "Hayat AI • Aktiv 📱",
    notificationHowAreYou: "Wie fühlst du dich gerade, mein Freund? 😊",
    notificationTapShortcut: "Klicke unten auf ein Kürzel, um Notizen oder Stimmung aufzuzeichnen.",
    write: "Schreiben",
    voiceRecord: "Sprache",
    mood: "Stimmung",
    advisor: "Berater",
    task: "Aufgabe",
    photo: "Foto",
    greetingTitle: "Willkommen und einen schönen Tag, mein Freund ☕",
    greetingDesc: "Heute ist ein neuer Tag für persönliches Wachstum. Notiere deine Gedanken für deinen Erfolg morgen.",
    fullCalendar: "Vollständiger Kalender & Tagesansicht 📅",
    fullCalendarSub: "Tagebücher, Bücher, Aktivitäten - klicke für alle Details",
    directUploadTitle: "Direkter Dateizugriff & Anhänge ⚡",
    attachPhoto: "Foto anhängen",
    attachPhotoSub: "Aus der Galerie",
    freeWrite: "Freies Schreiben",
    freeWriteSub: "Leeren Editor öffnen",
    audioFile: "Audiodatei",
    audioFileSub: "Aufnahme oder Audiodatei",
    phoneVideo: "Handyvideo",
    phoneVideoSub: "Videoclip hochladen",
    aiAdvisor: "KI-Berater",
    aiAdvisorSub: "Sofortige Analyse & Tipps",
    bookDoc: "Buch / Dokument",
    bookDocSub: "PDF oder Text hochladen",
    streakTitle: "Erfolgsreihe & Kontinuität",
    dayStreak: "Tage in Folge",
    streakEncouragement: "Großartig! Du hast heute Tagebuch geführt und deine Serie gehalten ✨",
    longestStreak: "Längste Serie",
    recentWeek: "Fortschritt der Woche",
    selectDateTitle: "Wähle ein Datum zum Erfassen oder Ansehen:",
    quoteTitle: "Tägliche Weisheit & Motivation 🌿",
    aiInspirationBtn: "(KI) Schlaue Inspiration 🪄",
    dhikrTitle: "Achtsamkeit & Geistige Reflexion 🌿",
    dhikrSub: "Nimm dir einen Moment für Dankbarkeit, Frieden und Entspannung ❤️",
    dhikrCounterBtn: "Hier tippen zum Zählen & Reflektieren 🪙",
    dhikrCountLabel: "Zähler:",
    dhikrFooter: "Dein Zählerstand bleibt dauerhaft gespeichert.",
    moodScaleTitle: "Schnelle digitale Stimmungsskala (1 - 10) 😐",
    moodScaleDesc: "Ziehe den Regler, um deine Stimmung sofort zu dokumentieren.",
    moodRating: "Stimmungsbewertung:",
    waterTrackerTitle: "Täglicher Wasser-Zähler 💧",
    waterTrackerDesc: "Tippe auf die Gläser, um getrunkenes Wasser zu erfassen. Trinken beruhigt das Nervensystem.",
    waterConsumed: "Getrunkene Menge:",
    waterRemaining: "Noch wenige Gläser bis zum Tagesziel 💡",
    symptomsTitle: "Körperliche Symptome ⚡",
    symptomsDesc: "Wähle körperliche Symptome aus, um Zusammenhänge zwischen Körper und Geist zu analysieren.",
    symptomRapidHeart: "Herzrasen 💓",
    symptomHeadache: "Kopfschmerzen / Druck 🤯",
    symptomShortnessBreath: "Kurzatmigkeit 🫁",
    symptomBackTension: "Muskel- & Rückenschmerzen 🧘",
    symptomFatigue: "Allgemeine Müdigkeit 🔋",
    symptomPoorSleep: "Schlafstörungen / Schlaflosigkeit 😴",
    symptomStomach: "Magenbeschwerden 🤢",
    symptomTremors: "Übermäßiges Schwitzen / Zittern 🥶",
    breathingTitle: "Box-Breathing Entspannungshelfer 🧘‍♂️",
    breathingDesc: "Wissenschaftlich bewährte Atemtechnik zur Beruhigung des Herzschlags (4 Sekunden pro Phase)",
    startBreathingBtn: "Atemübung starten ▶️",
    selfCareTitle: "Selbstfürsorge & Gesundheit 📝",
    sleepHours: "Schlafstunden 🌙",
    workoutMinutes: "Sport & Übungen 🏃",
    medicationDose: "Medikamente / Vitamine 💊",
    habitTitle: "Gewohnheiten & Routinen-Tracker 🎯",
    habitSub: "Wähle ein Datum und hake erledigte Gewohnheiten ab.",
    addHabitBtn: "Gewohnheit hinzufügen +",
    reportTitle: "KI-Verhaltensbewertung & Berichte 📊",
    reportDesc: "Wähle einen Zeitraum für deinen KI-Verhaltensbericht.",
    generateReportBtn: "KI-Verhaltensbericht erstellen 🧠",
    lifeMapTitle: "Lebenskarte & Gesundheitsindikatoren 📊",
    lifeMapSub: "Analysedashboard zur Verbindung von Routinen mit seelischer Gesundheit.",
    balanceIndex: "Täglicher Gesundheitsindex:",
    excellentBalance: "Hervorragende Balance",
    sleepQuality: "Schlafqualität 🌙",
    exerciseActivity: "Bewegung & Sport 🏃",
    medicationCompliance: "Medikamententreue 💊",
    subHabits: "Erfüllte Gewohnheiten 🎯",
    timelineTitle: "Integrierter Zeitstrahl & Schritte des Tages:",
    tipTitle: "Tages-Tipp für die psychische Gesundheit 💡",
    tipText: "Bei Prüfungsstress oder Angst hilft 1 Minute Box-Breathing (4s Einatmen, 4s Halten, 4s Ausatmen, 4s Halten), um den Vagusnerv sofort zu beruhigen.",
  },
  es: {
    appName: "Hayat AI",
    settingsTitle: "Ajustes Generales",
    settingsSubtitle: "Personaliza tu asistente inteligente, bloqueo de privacidad y sincronización",
    apiKeyTitle: "Tu clave API 🔑",
    floatingBallTitle: "Botón Flotante 🔘",
    backupTitle: "Copia de Seguridad y Sincronización ☁️",
    appLockTitle: "Bloqueo de Aplicación 🔐",
    favoritesTitle: "Notas Favoritas ⭐",
    remindersTitle: "Recordatorios y Alarmas ⏰",
    archiveTitle: "Archivo de Diarios 📥",
    trashTitle: "Papelera 🗑️",
    darkModeTitle: "Modo Oscuro ☀️/🌙",
    notificationsTitle: "Notificaciones 🔔",
    languagesTitle: "Idiomas de la App 🌐",
    rateTitle: "Valóranos 👍",
    contactTitle: "Contactar con el creador ✉️",
    homeTab: "Inicio",
    diariesTab: "Diarios",
    advisorTab: "Asesor",
    analyticsTab: "Estadísticas",
    settingsTab: "Ajustes",
    apiKeySub: "Estado de clave: Personalizada y activa localmente 🟢",
    apiKeySubAuto: "Estado de clave: Provista de forma segura por la nube ☁️",
    floatingBallSub: "Atajos rápidos y navegación para tu asistente de IA",
    backupSub: "Sincroniza y guarda tus diarios de forma segura",
    appLockSub: "Protege tus notas con un código PIN de 4 dígitos",
    favoritesSub: "Accede a tus diarios más importantes (4+ estrellas)",
    remindersSub: "Gestiona las alarmas de tareas y recordatorios diario",
    archiveSub: "Explora diarios archivados y antiguos",
    trashSub: "Restaura diarios eliminados recientemente",
    darkModeSub: "Activa el modo oscuro para proteger tus ojos",
    notificationsSub: "Recibe alertas periódicas para tus hábitos",
    languagesSub: "Cambiar el idioma de la interfaz",
    rateSub: "Ayúdanos a mejorar la aplicación con tu opinión",
    contactSub: "Envíanos tus valiosas sugerencias para mejorar",
    selectLanguageTitle: "Elige tu idioma 🌐",
    selectLanguageSubtitle: "Selecciona tu idioma preferido para la app, reconocimiento de voz e IA",
    confirmLanguage: "Continuar en este idioma 🚀",
    welcomeModalTitle: "Bienvenido a Hayat AI 👋",
    welcomeModalDesc: "Selecciona tu idioma preferido para personalizar la app y el asistente de IA.",

    notificationActiveNow: "Hayat AI • Activo 📱",
    notificationHowAreYou: "¿Cómo te sientes ahora mismo, mi amigo? 😊",
    notificationTapShortcut: "Toca un acceso directo para registrar tus notas o tu ánimo.",
    write: "Escribir",
    voiceRecord: "Voz",
    mood: "Ánimo",
    advisor: "Asesor",
    task: "Tarea",
    photo: "Foto",
    greetingTitle: "Bienvenido y feliz día, querido amigo ☕",
    greetingDesc: "Hoy es un nuevo día para crecer. Escribir tus pensamientos simples hoy ayuda a tu bienestar mañana.",
    fullCalendar: "Calendario completo & Vista diaria 📅",
    fullCalendarSub: "Diarios, libros, actividades - haz clic para explorar todo",
    directUploadTitle: "Acceso directo a archivos y adjuntos ⚡",
    attachPhoto: "Adjuntar foto",
    attachPhotoSub: "De la galería",
    freeWrite: "Escritura libre",
    freeWriteSub: "Abrir editor en blanco",
    audioFile: "Archivo de audio",
    audioFileSub: "Grabación o audio",
    phoneVideo: "Video móvil",
    phoneVideoSub: "Subir video",
    aiAdvisor: "Asesor IA",
    aiAdvisorSub: "Análisis y consejos al instante",
    bookDoc: "Libro / Documento",
    bookDocSub: "Subir PDF o texto",
    streakTitle: "Racha de registro y hábitos",
    dayStreak: "Días seguidos",
    streakEncouragement: "¡Excelente! Has escrito hoy y mantienes tu racha activa ✨",
    longestStreak: "Mejor racha histórica",
    recentWeek: "Progreso semanal",
    selectDateTitle: "Selecciona una fecha para ver o registrar actividades:",
    quoteTitle: "Sabiduría diaria & Motivación 🌿",
    aiInspirationBtn: "(IA) Inspiración inteligente 🪄",
    dhikrTitle: "Reflexión espiritual & Mindfulness 🌿",
    dhikrSub: "Tómate un momento para la paz, la gratitud y la calma interior ❤️",
    dhikrCounterBtn: "Toca aquí para contar y reflexionar 🪙",
    dhikrCountLabel: "Contador:",
    dhikrFooter: "Tu conteo se guarda permanentemente.",
    moodScaleTitle: "Medidor de estado de ánimo rápido (1 - 10) 😐",
    moodScaleDesc: "Desliza para registrar tu estado de ánimo al instante.",
    moodRating: "Evaluación del ánimo:",
    waterTrackerTitle: "Seguimiento diario de agua 💧",
    waterTrackerDesc: "Toca los vasos para registrar tu hidratación. Beber agua calma el sistema nervioso.",
    waterConsumed: "Cantidad consumida:",
    waterRemaining: "Unos pocos vasos para llegar al objetivo diario 💡",
    symptomsTitle: "Seguimiento de síntomas físicos ⚡",
    symptomsDesc: "Marca síntomas fisiológicos experimentados hoy para analizar conexiones cuerpo-mente.",
    symptomRapidHeart: "Taquicardia / Palpitaciones 💓",
    symptomHeadache: "Dolor de cabeza / Presión 🤯",
    symptomShortnessBreath: "Falta de aire 🫁",
    symptomBackTension: "Tensión muscular / Espalda 🧘",
    symptomFatigue: "Fatiga general 🔋",
    symptomPoorSleep: "Insomnio / Mala calidad de sueño 😴",
    symptomStomach: "Malestar estomacal 🤢",
    symptomTremors: "Sudoración excesiva / Temblores 🥶",
    breathingTitle: "Asistente de respiración cuadrada 🧘‍♂️",
    breathingDesc: "Técnica probada científicamente para calmar el ritmo cardíaco (4 segundos por fase)",
    startBreathingBtn: "Iniciar ejercicio de respiración ▶️",
    selfCareTitle: "Objetivos de autocuidado y salud mental 📝",
    sleepHours: "Horas de sueño 🌙",
    workoutMinutes: "Ejercicio / Deporte 🏃",
    medicationDose: "Dosis de medicina / Vitaminas 💊",
    habitTitle: "Seguimiento de hábitos y rutinas 🎯",
    habitSub: "Selecciona una fecha y marca tus hábitos completados.",
    addHabitBtn: "Agregar hábito +",
    reportTitle: "Evaluación conductual de IA 📊",
    reportDesc: "Selecciona un rango de tiempo para generar un informe de conducta con IA.",
    generateReportBtn: "Generar informe con IA 🧠",
    lifeMapTitle: "Mapa de vida e indicadores de salud 📊",
    lifeMapSub: "Panel analítico conectando hábitos con bienestar emocional.",
    balanceIndex: "Índice de equilibrio diario:",
    excellentBalance: "Equilibrio excelente",
    sleepQuality: "Calidad del sueño 🌙",
    exerciseActivity: "Ejercicio y movimiento 🏃",
    medicationCompliance: "Cumplimiento de medicación 💊",
    subHabits: "Hábitos completados 🎯",
    timelineTitle: "Línea de tiempo integrada & Pasos del día:",
    tipTitle: "Consejo de salud mental del día 💡",
    tipText: "En momentos de estrés, practica 1 minuto de respiración cuadrada (Inhala 4s, Mantén 4s, Exhala 4s, Mantén 4s) para calmar el sistema nervioso.",
  },
  tr: {
    appName: "Hayat AI",
    settingsTitle: "Genel Ayarlar",
    settingsSubtitle: "Akıllı asistanınızı, PIN kilidinizi ve veri senkronizasyonunu özelleştirin",
    apiKeyTitle: "API Anahtarınız 🔑",
    floatingBallTitle: "Yüzen Düğmeyi Göster 🔘",
    backupTitle: "Yedekleme ve Senkronizasyon ☁️",
    appLockTitle: "Uygulama Kilidi 🔐",
    favoritesTitle: "Favori Notlar ⭐",
    remindersTitle: "Hatırlatıcılar ve Alarmlar ⏰",
    archiveTitle: "Günlük Arşivi 📥",
    trashTitle: "Çöp Kutusu 🗑️",
    darkModeTitle: "Karanlık Mod ☀️/🌙",
    notificationsTitle: "Bildirimler 🔔",
    languagesTitle: "Uygulama Dilleri 🌐",
    rateTitle: "Bizi Değerlendirin 👍",
    contactTitle: "Geliştirici ile İletişim ✉️",
    homeTab: "Ana Sayfa",
    diariesTab: "Günlükler",
    advisorTab: "Danışman",
    analyticsTab: "Analizler",
    settingsTab: "Ayarlar",
    apiKeySub: "Anahtar durumu: Özel & yerel olarak aktif 🟢",
    apiKeySubAuto: "Anahtar durumu: Bulut tarafından güvenle sağlandı ☁️",
    floatingBallSub: "Yapay zeka asistanı için hızlı navigasyon kısayolları",
    backupSub: "Günlüklerinizi yerel ve bulutta güvenle yedekleyin",
    appLockSub: "Notlarınızı 4 haneli PIN koduyla koruyun",
    favoritesSub: "En önemli günlüklerinize hızla erişin (4+ yıldız)",
    remindersSub: "Zamanlanmış görev alarmlarınızı yönetin",
    archiveSub: "Arşivlenmiş eski günlüklerinize göz atın",
    trashSub: "Son silinen günlüklerinizi geri yükleyin",
    darkModeSub: "Gözlerinizi korumak için karanlık modu açın",
    notificationsSub: "Alışkanlıklar için düzenli bildirimler alın",
    languagesSub: "Uygulama arayüz dilini değiştirin",
    rateSub: "Geri bildiriminizle uygulamayı geliştirmemize yardımcı olun",
    contactSub: "Değerli önerilerinizi bize iletin",
    selectLanguageTitle: "Dilinizi Seçin 🌐",
    selectLanguageSubtitle: "Uygulama arayüzü, ses tanıma ve AI asistanı için dilinizi seçin",
    confirmLanguage: "Bu dilde devam et 🚀",
    welcomeModalTitle: "Hayat AI'ya Hoş Geldiniz 👋",
    welcomeModalDesc: "Uygulama ve yapay zeka asistanını kişiselleştirmek için lütfen dilinizi seçin.",

    notificationActiveNow: "Hayat AI • Aktif 📱",
    notificationHowAreYou: "Şu an nasıl hissediyorsun dostum? 😊",
    notificationTapShortcut: "Not almak veya ruh halinizi kaydetmek için aşağıdaki kısayollara dokunun.",
    write: "Yaz",
    voiceRecord: "Ses",
    mood: "Ruh Hali",
    advisor: "Danışman",
    task: "Görev",
    photo: "Fotoğraf",
    greetingTitle: "Hoş geldin, iyi günler değerli dostum ☕",
    greetingDesc: "Bugün gelişim için yeni bir gün. Düşüncelerini kaydetmek yarın için sana yol gösterir.",
    fullCalendar: "Tam Takvim & Günlük Görünüm 📅",
    fullCalendarSub: "Günlükler, kitaplar, aktiviteler - her günü incelemek için tıklayın",
    directUploadTitle: "Doğrudan Dosya Erişimi & Ekler ⚡",
    attachPhoto: "Fotoğraf Ekle",
    attachPhotoSub: "Galeriden seç",
    freeWrite: "Serbest Yazı",
    freeWriteSub: "Boş editör aç",
    audioFile: "Ses Dosyası",
    audioFileSub: "Ses kaydı yükle",
    phoneVideo: "Telefon Videosu",
    phoneVideoSub: "Video klip yükle",
    aiAdvisor: "AI Danışman",
    aiAdvisorSub: "Anında analiz & öneriler",
    bookDoc: "Kitap / Belge",
    bookDocSub: "PDF veya metin yükle",
    streakTitle: "Günlük Yazma Serisi",
    dayStreak: "Üst Üste Gün",
    streakEncouragement: "Harika! Bugün günlük tuttun ve serini korudun ✨",
    longestStreak: "En Uzun Seri Rekoru",
    recentWeek: "Haftalık Takip",
    selectDateTitle: "İşlem yapmak veya görüntülemek için tarih seçin:",
    quoteTitle: "Günün Sözü & Motivasyon 🌿",
    aiInspirationBtn: "(AI) Akıllı İlham 🪄",
    dhikrTitle: "Zikir & Ruhsal Huzur Köşesi 🌿",
    dhikrSub: "Huzur, şükür ve içsel dinginlik için bir an ayırın ❤️",
    dhikrCounterBtn: "Zikir sayacı için buraya dokunun 🪙",
    dhikrCountLabel: "Sayaç:",
    dhikrFooter: "Sayacınız kalıcı olarak kaydedilir.",
    moodScaleTitle: "Hızlı Dijital Ruh Hali Ölçeği (1 - 10) 😐",
    moodScaleDesc: "Ruh halinizi anında kaydetmek için kaydırıcıyı çekin.",
    moodRating: "Ruh Hali Puanı:",
    waterTrackerTitle: "Günlük İnteraktif Su Sayacı 💧",
    waterTrackerDesc: "İçtiğiniz su miktarını kaydetmek için bardaklara dokunun.",
    waterConsumed: "Tüketilen Miktar:",
    waterRemaining: "Günlük hedefe ulaşmak için birkaç bardak kaldı 💡",
    symptomsTitle: "Fiziksel Belirti Takibi ⚡",
    symptomsDesc: "Beden-zihin ilişkisini analiz etmek için bugün hissettiğiniz belirtileri seçin.",
    symptomRapidHeart: "Hızlı Kalp Atışı 💓",
    symptomHeadache: "Baş Ağrısı / Basınç 🤯",
    symptomShortnessBreath: "Nefes Darlığı 🫁",
    symptomBackTension: "Kas & Sırt Ağrısı 🧘",
    symptomFatigue: "Genel Yorgunluk 🔋",
    symptomPoorSleep: "Uykusuzluk / Kötü Uyku 😴",
    symptomStomach: "Mide Rahatsızlığı 🤢",
    symptomTremors: "Aşırı Terleme / Titreme 🥶",
    breathingTitle: "Kutu Nefesi Rahatlama Asistanı 🧘‍♂️",
    breathingDesc: "Kalp atışını yavaşlatmak için bilimsel olarak kanıtlanmış yöntem (her evre 4 saniye)",
    startBreathingBtn: "Nefes Egzersizini Başlat ▶️",
    selfCareTitle: "Öz Bakım & Ruh Sağlığı Hedefleri 📝",
    sleepHours: "Uyku Saatleri 🌙",
    workoutMinutes: "Egzersiz & Spor 🏃",
    medicationDose: "İlaç / Vitamin Dozu 💊",
    habitTitle: "Davranışsal Alışkanlık Takibi 🎯",
    habitSub: "Tarih seçin ve tamamlanan alışkanlıklarınızı işaretleyin.",
    addHabitBtn: "Alışkanlık Ekle +",
    reportTitle: "Yapay Zeka Alışkanlık Raporu 📊",
    reportDesc: "AI ile davranışsal analiz raporu oluşturmak için zaman aralığı seçin.",
    generateReportBtn: "AI Raporu Oluştur 🧠",
    lifeMapTitle: "Yaşam Haritası & Sağlık Göstergeleri 📊",
    lifeMapSub: "Alışkanlıklar ve ruh sağlığını bağlayan analitik panel.",
    balanceIndex: "Günlük Denge İndeksi:",
    excellentBalance: "Mükemmel Denge",
    sleepQuality: "Uyku Kalitesi 🌙",
    exerciseActivity: "Hareket & Spor 🏃",
    medicationCompliance: "İlaç Uyumu 💊",
    subHabits: "Tamamlanan Alışkanlıklar 🎯",
    timelineTitle: "Entegre Zaman Çizelgesi & Günün Adımları:",
    tipTitle: "Günün Ruh Sağlığı İpucu 💡",
    tipText: "Stres anlarında 1 dakika Kutu Nefesi yapın (4sn Al, 4sn Tut, 4sn Ver, 4sn Tut) sinir sisteminizi anında sakinleştirin.",
  },
  ur: {
    appName: "حياة AI",
    settingsTitle: "عمومی ترتیبات",
    settingsSubtitle: "اپنے ذہین اسسٹنٹ، سیکیورٹی لاک، اور ڈیٹا سنک کو حسب ضرورت بنائیں",
    apiKeyTitle: "آپ کی API کی 🔑",
    floatingBallTitle: "فلوٹنگ بٹن 🔘",
    backupTitle: "بیک اپ اور سنکرونائزیشن ☁️",
    appLockTitle: "ایپ لاک 🔐",
    favoritesTitle: "پسندیدہ نوٹس ⭐",
    remindersTitle: "تذکیرات اور الارم ⏰",
    archiveTitle: "ڈائری آرکائیو 📥",
    trashTitle: "ری سائیکل بن 🗑️",
    darkModeTitle: "ڈارک موڈ ☀️/🌙",
    notificationsTitle: "نوٹیفیکیشنز 🔔",
    languagesTitle: "ایپ کی زبانیں 🌐",
    rateTitle: "ہمیں ریٹ کریں 👍",
    contactTitle: "ڈویلپر سے رابطہ کریں ✉️",
    homeTab: "ہوم",
    diariesTab: "ڈائریز",
    advisorTab: "مشیر AI",
    analyticsTab: "تجزیات",
    settingsTab: "ترتیبات",
    apiKeySub: "کی سٹیٹس: لوکل ایکٹیو 🟢",
    apiKeySubAuto: "کی سٹیٹس: کلاؤڈ کے ذریعے محفوظ خودکار ☁️",
    floatingBallSub: "AI اسسٹنٹ کے لیے تیز رفتار نیویگیشن شارٹ کٹس",
    backupSub: "اپنی ڈائریوں کو لوکل اور کلاؤڈ پر محفوظ کریں",
    appLockSub: "4 ہندسوں والے PIN کے ساتھ اپنے نوٹس محفوظ کریں",
    favoritesSub: "اپنی اہم ترین ڈائریوں تک فوری رسائی (4+ اسٹارز)",
    remindersSub: "شیڈول شدہ کاموں اور الٹیرٹس کا نظم کریں",
    archiveSub: "پرانی اور محفوظ شدہ ڈائریوں کو دیکھیں",
    trashSub: "حالیہ حذف شدہ ڈائریوں کو بحال کریں",
    darkModeSub: "آنکھوں کی حفاظت کے لیے ڈارک موڈ فعال کریں",
    notificationsSub: "عادات کے لیے باقاعدہ نوٹیفیکیشنز حاصل کریں",
    languagesSub: "ایپلی کیشن کا انٹرفیس تبدیل کریں",
    rateSub: "ایپ کو مزید بہتر بنانے میں ہماری مدد کریں",
    contactSub: "اپنی قیمتی تجاویز اور آراء بھیجیں",
    selectLanguageTitle: "اپنی زبان منتخب کریں 🌐",
    selectLanguageSubtitle: "ایپ انٹرفیس، آواز کی شناخت اور AI مشیر کے لیے زبان کا انتخاب کریں",
    confirmLanguage: "اس زبان میں جاری رکھیں 🚀",
    welcomeModalTitle: "حياة AI میں خوش آمدید 👋",
    welcomeModalDesc: "برائے مہربانی اپنی پسندیدہ زبان منتخب کریں تا کہ ایپ اور AI اسسٹنٹ آپ کی زبان میں کام کر سکے۔",

    notificationActiveNow: "حياة AI • فعال 📱",
    notificationHowAreYou: "آپ ابھی کیسا محسوس کر رہے ہیں میرے دوست؟ 😊",
    notificationTapShortcut: "نوٹ لکھنے یا مزاج ریکارڈ کرنے کے لیے نیچے کسی شارٹ کٹ پر ٹیپ کریں۔",
    write: "تحریر",
    voiceRecord: "آواز",
    mood: "مزاج",
    advisor: "مشیر",
    task: "کام",
    photo: "تصویر",
    greetingTitle: "خوش آمدید، آپ کا دن اچھا گزرے میرے دوست ☕",
    greetingDesc: "آج کا دن ذاتی ترقی اور خود شناسی کے لیے نیا موقع ہے۔",
    fullCalendar: "مکمل کیلنڈر اور روزانہ کا جائزہ 📅",
    fullCalendarSub: "ڈائریز، کتب، سرگرمیاں - ہر دن کا جائزہ لینے کے لیے کلک کریں",
    directUploadTitle: "فائلوں اور اٹیچمنٹس تک براہ راست رسائی ⚡",
    attachPhoto: "تصویر اٹیچ کریں",
    attachPhotoSub: "گیلری سے",
    freeWrite: "آزاد تحریر",
    freeWriteSub: "خالی ایڈیٹر کھولیں",
    audioFile: "آڈیو فائل",
    audioFileSub: "ریکارڈنگ یا آڈیو فائل",
    phoneVideo: "فون ویڈیو",
    phoneVideoSub: "ویڈیو کلپ اپ لوڈ کریں",
    aiAdvisor: "AI مشیر",
    aiAdvisorSub: "فوری تجزیہ اور تجاویز",
    bookDoc: "کتاب / دستاویز",
    bookDocSub: "PDF یا ٹیکسٹ اپ لوڈ کریں",
    streakTitle: "روزانہ ڈائری لکھنے تسلسل",
    dayStreak: "مسلسل دن",
    streakEncouragement: "بہت خوب! آپ نے آج اپنی ڈائری لکھی اور اپنا تسلسل برقرار رکھا ✨",
    longestStreak: "طویل ترین تاریخی تسلسل",
    recentWeek: "حالیہ ہفتے کی پیشرفت",
    selectDateTitle: "سرگرمیاں ریکارڈ یا دیکھنے کے لیے تاریخ منتخب کریں:",
    quoteTitle: "آج کی دانشمندی اور ترغیب 🌿",
    aiInspirationBtn: "(AI) ذہین الہام 🪄",
    dhikrTitle: "اذکار اور روحانی گوشہ 🌿",
    dhikrSub: "سکون، شکر اور روحانی تسکین کے لیے کچھ وقت نکالیں ❤️",
    dhikrCounterBtn: "تسبیح اور ذکر کے لیے یہاں کلک کریں 🪙",
    dhikrCountLabel: "کاؤنٹر:",
    dhikrFooter: "آپ کی گنتی ہمیشہ محفوظ رہتی ہے۔",
    moodScaleTitle: "فوری ڈیجیٹل موڈ سکیل (1 - 10) 😐",
    moodScaleDesc: "اپنے موڈ کو فوری ریکارڈ کرنے کے لیے سلائیڈر کو ڈریگ کریں۔",
    moodRating: "موڈ کی درجہ بندی:",
    waterTrackerTitle: "روزانہ پانی کا کاؤنٹر 💧",
    waterTrackerDesc: "پانی کی مقدار ریکارڈ کرنے کے لیے کپ پر کلک کریں۔",
    waterConsumed: "استعمال شدہ مقدار:",
    waterRemaining: "بہترین حد تک پہنچنے کے لیے کچھ کپ باقی ہیں 💡",
    symptomsTitle: "جسمانی علامات کا ٹریکر ⚡",
    symptomsDesc: "آج محسوس ہونے والی جسمانی علامات منتخب کریں تاکہ AI ان کا تجزیہ کر سکے۔",
    symptomRapidHeart: "دل کی دھڑکن تیز ہونا 💓",
    symptomHeadache: "سر درد / دباؤ 🤯",
    symptomShortnessBreath: "سانس کی تنگی 🫁",
    symptomBackTension: "پٹھوں کا کھنچاؤ / کمر درد 🧘",
    symptomFatigue: "عام تھکن 🔋",
    symptomPoorSleep: "بے خوابی / نیند کی کمی 😴",
    symptomStomach: "معدے کی خرابی 🤢",
    symptomTremors: "زیادہ پسینہ / کپکپی 🥶",
    breathingTitle: "سانس کی مشق کا اسسٹنٹ 🧘‍♂️",
    breathingDesc: "دل کی دھڑکن کو پرسکون کرنے کا سائنسی طریقہ (ہر مرحلہ 4 سیکنڈ)",
    startBreathingBtn: "مشق شروع کریں ▶️",
    selfCareTitle: "ذاتی دیکھ بھال کے اہداف 📝",
    sleepHours: "نیند کے گھنٹے 🌙",
    workoutMinutes: "ورزش اور کھیل 🏃",
    medicationDose: "دوائی / وٹامن کی خوراک 💊",
    habitTitle: "عادات کا ٹریکر 🎯",
    habitSub: "تاریخ منتخب کریں اور مکمل عادات کو مارک کریں۔",
    addHabitBtn: "عادت شامل کریں +",
    reportTitle: "AI رویے کا رپورٹ تجزیہ 📊",
    reportDesc: "AI رپورٹ تیار کرنے کے لیے وقت کا انتخاب کریں۔",
    generateReportBtn: "AI رپورٹ بنائیں 🧠",
    lifeMapTitle: "لائف میپ اور صحت کے اشارے 📊",
    lifeMapSub: "عادات اور ذہنی صحت کو جوڑنے والا تجزیاتی پینل۔",
    balanceIndex: "روزانہ صحت و توازن کا اشاریہ:",
    excellentBalance: "بہترین توازن",
    sleepQuality: "نیند کا معیار 🌙",
    exerciseActivity: "حرکت اور ورزش 🏃",
    medicationCompliance: "ادویات کی پابندی 💊",
    subHabits: "مکمل شدہ عادات 🎯",
    timelineTitle: "آج کے اقدامات کی ٹائم لائن:",
    tipTitle: "آج کی ذہنی صحت کی ٹیپ 💡",
    tipText: "تناؤ کی صورت میں 1 منٹ باکس بریدھنگ مشق کریں (4 سیکنڈ سانس لیں، 4 سیکنڈ روکیں، 4 سیکنڈ چھوڑیں، 4 سیکنڈ روکیں)۔",
  },
  ru: {
    appName: "Hayat AI",
    settingsTitle: "Общие настройки",
    settingsSubtitle: "Настройте умного ассистента, PIN-код и синхронизацию данных",
    apiKeyTitle: "Ваш API-ключ 🔑",
    floatingBallTitle: "Плавающая кнопка 🔘",
    backupTitle: "Резервное копирование и синхронизация ☁️",
    appLockTitle: "Блокировка приложения 🔐",
    favoritesTitle: "Избранные заметки ⭐",
    remindersTitle: "Напоминания и будильники ⏰",
    archiveTitle: "Архив дневников 📥",
    trashTitle: "Корзина 🗑️",
    darkModeTitle: "Тёмная тема ☀️/🌙",
    notificationsTitle: "Уведомления 🔔",
    languagesTitle: "Языки приложения 🌐",
    rateTitle: "Оцените нас 👍",
    contactTitle: "Связаться с разработчиком ✉️",
    homeTab: "Главная",
    diariesTab: "Дневники",
    advisorTab: "Советник",
    analyticsTab: "Аналитика",
    settingsTab: "Настройки",
    apiKeySub: "Статус ключа: Настроен и активен локально 🟢",
    apiKeySubAuto: "Статус ключа: Безопасно предоставляется облаком ☁️",
    floatingBallSub: "Быстрый доступ к функциям ИИ-ассистента",
    backupSub: "Синхронизируйте и сохраняйте записи в облаке",
    appLockSub: "Защитите записи 4-значным PIN-кодом",
    favoritesSub: "Быстрый доступ к самым важным записям (4+ звезды)",
    remindersSub: "Управление напоминаниями и задачами",
    archiveSub: "Просмотр архивных и старых записей",
    trashSub: "Восстановление недавно удаленных записей",
    darkModeSub: "Включите тёмную тему для защиты глаз",
    notificationsSub: "Получайте регулярные напоминания о привычках",
    languagesSub: "Изменить язык интерфейса приложения",
    rateSub: "Помогите нам улучшить приложение вашим отзывом",
    contactSub: "Отправьте нам ваши ценные предложения",
    selectLanguageTitle: "Выберите ваш язык 🌐",
    selectLanguageSubtitle: "Выберите язык интерфейса, распознавания речи и ИИ-ассистента",
    confirmLanguage: "Продолжить на этом языке 🚀",
    welcomeModalTitle: "Добро пожаловать в Hayat AI 👋",
    welcomeModalDesc: "Пожалуйста, выберите предпочитаемый язык для персонализации приложения и ИИ.",

    notificationActiveNow: "Hayat AI • Активно 📱",
    notificationHowAreYou: "Как ты себя чувствуешь прямо сейчас, друг? 😊",
    notificationTapShortcut: "Нажми на ярлык ниже, чтобы записать мысли или настроение.",
    write: "Запись",
    voiceRecord: "Голос",
    mood: "Настроение",
    advisor: "Советник",
    task: "Задача",
    photo: "Фото",
    greetingTitle: "Добро пожаловать и хорошего дня, дорогой друг ☕",
    greetingDesc: "Сегодня новый день для роста. Запись мыслей сегодня даёт лучшую аналитику завтра.",
    fullCalendar: "Календарь и Просмотр дней 📅",
    fullCalendarSub: "Дневники, книги, активности - нажми для подробностей",
    directUploadTitle: "Быстрый доступ к файлам и вложениям ⚡",
    attachPhoto: "Прикрепить фото",
    attachPhotoSub: "Из галереи",
    freeWrite: "Свободное письмо",
    freeWriteSub: "Открыть пустой редактор",
    audioFile: "Аудиофайл",
    audioFileSub: "Запись или аудио",
    phoneVideo: "Видео",
    phoneVideoSub: "Загрузить видеоролик",
    aiAdvisor: "ИИ-Советник",
    aiAdvisorSub: "Мгновенный анализ и советы",
    bookDoc: "Книга / Документ",
    bookDocSub: "Загрузить PDF или текст",
    streakTitle: "Серия записей и привычек",
    dayStreak: "Дней подряд",
    streakEncouragement: "Отлично! Ты сделал запись сегодня и сохранил прогресс ✨",
    longestStreak: "Рекордная серия",
    recentWeek: "Прогресс за неделю",
    selectDateTitle: "Выберите дату для записи или просмотра:",
    quoteTitle: "Мудрость дня и Мотивация 🌿",
    aiInspirationBtn: "(ИИ) Умное вдохновение 🪄",
    dhikrTitle: "Духовность и Осознанность 🌿",
    dhikrSub: "Уделите минуту спокойствию, благодарности и внутренней гармонии ❤️",
    dhikrCounterBtn: "Нажмите здесь для подсчета и медитации 🪙",
    dhikrCountLabel: "Счётчик:",
    dhikrFooter: "Ваш счёт сохраняется навсегда.",
    moodScaleTitle: "Быстрый трекер настроения (1 - 10) 😐",
    moodScaleDesc: "Перетащите ползунок для фиксации настроения за 1 секунду.",
    moodRating: "Оценка настроения:",
    waterTrackerTitle: "Ежедневный счётчик воды 💧",
    waterTrackerDesc: "Нажимайте на стаканы, чтобы отмечать выпитую воду. Вода успокаивает нервную систему.",
    waterConsumed: "Выпито:",
    waterRemaining: "Осталось немного до идеальной нормы 💡",
    symptomsTitle: "Физические симптомы ⚡",
    symptomsDesc: "Отметьте симптомы, испытываемые сегодня, для анализа связи тела и разума.",
    symptomRapidHeart: "Учащенное сердцебиение 💓",
    symptomHeadache: "Головная боль / Давление 🤯",
    symptomShortnessBreath: "Одышка / Затрудненное дыхание 🫁",
    symptomBackTension: "Мышечное напряжение / Боль в спине 🧘",
    symptomFatigue: "Общая усталость 🔋",
    symptomPoorSleep: "Бессонница / Плохой сон 😴",
    symptomStomach: "Боль в животе 🤢",
    symptomTremors: "Повышенное потоотделение / Дрожь 🥶",
    breathingTitle: "Квадратное дыхание для расслабления 🧘‍♂️",
    breathingDesc: "Научно доказанный метод замедления пульса (4 секунды на каждый этап)",
    startBreathingBtn: "Начать дыхание ▶️",
    selfCareTitle: "Цели заботы о себе и здоровья 📝",
    sleepHours: "Часы сна 🌙",
    workoutMinutes: "Спорт и упражнения 🏃",
    medicationDose: "Лекарства / Витамины 💊",
    habitTitle: "Трекер привычек и рутины 🎯",
    habitSub: "Выберите дату и отметьте выполненные привычки.",
    addHabitBtn: "Добавить привычку +",
    reportTitle: "ИИ-Отчёт о поведении 📊",
    reportDesc: "Выберите период для генерации ИИ-анализа вашего поведения.",
    generateReportBtn: "Создать отчёт ИИ 🧠",
    lifeMapTitle: "Карта жизни и Показатели здоровья 📊",
    lifeMapSub: "Аналитическая панель связи привычек и душевного здоровья.",
    balanceIndex: "Индекс баланса здоровья:",
    excellentBalance: "Отличный баланс",
    sleepQuality: "Качество сна 🌙",
    exerciseActivity: "Активность и спорт 🏃",
    medicationCompliance: "Прием лекарств 💊",
    subHabits: "Выполнение привычек 🎯",
    timelineTitle: "Интегрированная хронология дня:",
    tipTitle: "Совет дня по психическому здоровью 💡",
    tipText: "При стрессе выполняйте 1 минуту квадратного дыхания (вдох 4с, задержка 4с, выдох 4с, задержка 4с) для мгновенного успокоения нервной системы.",
  },
  zh: {
    appName: "Hayat AI",
    settingsTitle: "通用设置",
    settingsSubtitle: "自定义您的智能助手、密码锁和数据同步",
    apiKeyTitle: "您的 API 密钥 🔑",
    floatingBallTitle: "显示悬浮球 🔘",
    backupTitle: "备份与同步 ☁️",
    appLockTitle: "应用锁 🔐",
    favoritesTitle: "收藏笔记 ⭐",
    remindersTitle: "提醒与闹钟 ⏰",
    archiveTitle: "日记归档 📥",
    trashTitle: "回收站 🗑️",
    darkModeTitle: "深色模式 ☀️/🌙",
    notificationsTitle: "通知 🔔",
    languagesTitle: "应用语言 🌐",
    rateTitle: "评价我们 👍",
    contactTitle: "联系开发者 ✉️",
    homeTab: "首页",
    diariesTab: "日记",
    advisorTab: "AI顾问",
    analyticsTab: "数据分析",
    settingsTab: "设置",
    apiKeySub: "密钥状态：自定义并在本地激活 🟢",
    apiKeySubAuto: "密钥状态：由云端安全自动提供 ☁️",
    floatingBallSub: "快捷导航与AI助手控制",
    backupSub: "安全备份您的日记到本地和云端",
    appLockSub: "使用 4 位 PIN 码保护您的隐私",
    favoritesSub: "快速浏览最重要的日记（4星及以上）",
    remindersSub: "管理日程提醒与日常任务",
    archiveSub: "浏览已归档的旧日记",
    trashSub: "恢复最近删除的日记",
    darkModeSub: "开启深色模式保护眼睛",
    notificationsSub: "接收习惯与日记的定期提醒",
    languagesSub: "更改应用程序界面语言",
    rateSub: "提出宝贵意见，帮助我们做得更好",
    contactSub: "向我们发送您的建议与反馈",
    selectLanguageTitle: "选择您的语言 🌐",
    selectLanguageSubtitle: "选择界面、语音识别和 AI 助手的偏好语言",
    confirmLanguage: "使用此语言继续 🚀",
    welcomeModalTitle: "欢迎使用 Hayat AI 👋",
    welcomeModalDesc: "请选择您的偏好语言以个性化应用和 AI 助手。",

    notificationActiveNow: "Hayat AI • 当前在线 📱",
    notificationHowAreYou: "朋友，你现在感觉怎么样？ 😊",
    notificationTapShortcut: "点击下方快捷键立即记录笔记或心情。",
    write: "写作",
    voiceRecord: "语音",
    mood: "心情",
    advisor: "顾问",
    task: "任务",
    photo: "照片",
    greetingTitle: "欢迎您，祝您今天愉快 ☕",
    greetingDesc: "今天是成长与自我和解的新一天。记录简单想法，为明天带来最佳建议。",
    fullCalendar: "完整日历与每日回顾 📅",
    fullCalendarSub: "日记、书籍、活动 - 点击查看任意日期的记录",
    directUploadTitle: "文件与附件直接访问 ⚡",
    attachPhoto: "附加照片",
    attachPhotoSub: "来自相册",
    freeWrite: "自由写作",
    freeWriteSub: "打开空白编辑器",
    audioFile: "音频文件",
    audioFileSub: "录音或音频文件",
    phoneVideo: "手机视频",
    phoneVideoSub: "上传视频剪辑",
    aiAdvisor: "AI 顾问",
    aiAdvisorSub: "即时分析与建议",
    bookDoc: "书籍 / 文档",
    bookDocSub: "上传 PDF 或文本",
    streakTitle: "连续打卡与记录",
    dayStreak: "天连续",
    streakEncouragement: "太棒了！你今天记录了想法并保持了连续打卡 ✨",
    longestStreak: "历史最长连续打卡",
    recentWeek: "本周进度跟踪",
    selectDateTitle: "选择日期以记录或查看活动：",
    quoteTitle: "每日智慧与心理激励 🌿",
    aiInspirationBtn: "(AI) 智能灵感 🪄",
    dhikrTitle: "正念与精神冥想 🌿",
    dhikrSub: "抽出片刻享受宁静、感恩与内心平和 ❤️",
    dhikrCounterBtn: "点击此处进行计数与正念冥想 🪙",
    dhikrCountLabel: "计数器：",
    dhikrFooter: "您的计数记录将永久保存。",
    moodScaleTitle: "快速数字情绪跟踪器 (1 - 10) 😐",
    moodScaleDesc: "拖动滑块在 1 秒内记录您的心情，AI 将其纳入每日健康评估。",
    moodRating: "心情评分：",
    waterTrackerTitle: "每日互动饮水计数器 💧",
    waterTrackerDesc: "点击水杯记录饮水量。补充水分有助于平复神经系统。",
    waterConsumed: "已饮用量：",
    waterRemaining: "还差几杯即可达到每日最佳目标 💡",
    symptomsTitle: "身体症状跟踪 ⚡",
    symptomsDesc: "勾选今天体验到的生理症状，帮助 AI 分析身心关联。",
    symptomRapidHeart: "心跳过速 💓",
    symptomHeadache: "头痛 / 头部压迫感 🤯",
    symptomShortnessBreath: "呼吸急促 🫁",
    symptomBackTension: "肌肉与背部紧张 🧘",
    symptomFatigue: "全身疲劳 🔋",
    symptomPoorSleep: "失眠 / 睡眠质量差 😴",
    symptomStomach: "肠胃不适 🤢",
    symptomTremors: "多汗 / 发抖 🥶",
    breathingTitle: "箱式呼吸放松助手 🧘‍♂️",
    breathingDesc: "经科学验证的减缓心率放松法（每阶段 4 秒）",
    startBreathingBtn: "开始呼吸练习 ▶️",
    selfCareTitle: "自我关怀与心理健康目标 📝",
    sleepHours: "睡眠时长 🌙",
    workoutMinutes: "运动与健身 🏃",
    medicationDose: "药物 / 维生素剂量 💊",
    habitTitle: "行为习惯与日常跟踪 🎯",
    habitSub: "选择日期并勾选已完成习惯，提升自律。",
    addHabitBtn: "添加习惯 +",
    reportTitle: "AI 行为评估报告 📊",
    reportDesc: "选择时间段，生成 AI 行为趋势评估报告。",
    generateReportBtn: "生成 AI 行为报告 🧠",
    lifeMapTitle: "生活地图与健康指标 📊",
    lifeMapSub: "连接习惯与心理健康质量的综合分析面板。",
    balanceIndex: "每日健康平衡指数：",
    excellentBalance: "良好平衡",
    sleepQuality: "睡眠质量 🌙",
    exerciseActivity: "运动与活动 🏃",
    medicationCompliance: "服药依从性 💊",
    subHabits: "习惯完成度 🎯",
    timelineTitle: "整合时间轴与今日步骤：",
    tipTitle: "今日心理健康小贴士 💡",
    tipText: "感到压力或焦虑时，练习 1 分钟箱式呼吸（吸气4秒，屏气4秒，呼气4秒，屏气4秒）以快速平复神经系统。",
  },
  ja: {
    appName: "Hayat AI",
    settingsTitle: "一般設定",
    settingsSubtitle: "AI アシスタント、パスコードロック、同期のカスタマイズ",
    apiKeyTitle: "API キー 🔑",
    floatingBallTitle: "フローティングボタン表示 🔘",
    backupTitle: "バックアップと同期 ☁️",
    appLockTitle: "アプリロック 🔐",
    favoritesTitle: "お気に入りノート ⭐",
    remindersTitle: "リマインダーとアラーム ⏰",
    archiveTitle: "日記アーカイブ 📥",
    trashTitle: "ゴミ箱 🗑️",
    darkModeTitle: "ダークモード ☀️/🌙",
    notificationsTitle: "通知 🔔",
    languagesTitle: "アプリの言語 🌐",
    rateTitle: "アプリを評価 👍",
    contactTitle: "開発者に連絡 ✉️",
    homeTab: "ホーム",
    diariesTab: "日記",
    advisorTab: "AI相談員",
    analyticsTab: "分析",
    settingsTab: "設定",
    apiKeySub: "キー状態: カスタム & ローカルでアクティブ 🟢",
    apiKeySubAuto: "キー状態: クラウド経由で自動供給 ☁️",
    floatingBallSub: "AIアシスタントへのクイックアクセスショートカット",
    backupSub: "日記をローカルおよびクラウドに安全にバックアップ",
    appLockSub: "4桁のPINコードでノートを保護",
    favoritesSub: "最も重要な日記にクイックアクセス（星4以上）",
    remindersSub: "スケジュールされたタスクのアラームを管理",
    archiveSub: "アーカイブされた古い日記を閲覧",
    trashSub: "最近削除した日記を復元",
    darkModeSub: "目に優しいダークモードを有効化",
    notificationsSub: "習慣のリマインダー通知を受け取る",
    languagesSub: "アプリのユーザーインターフェース言語を変更",
    rateSub: "フィードバックでアプリの改善にご協力ください",
    contactSub: "開発者にご意見・ご要望を送信",
    selectLanguageTitle: "言語を選択してください 🌐",
    selectLanguageSubtitle: "UI、音声認識、AIアシスタントの言語を選択します",
    confirmLanguage: "この言語で続ける 🚀",
    welcomeModalTitle: "Hayat AI へようこそ 👋",
    welcomeModalDesc: "アプリやAIアシスタントを最適化するため、お好みの言語を選択してください。",

    notificationActiveNow: "Hayat AI • アクティブ 📱",
    notificationHowAreYou: "今の気分はいかがですか？ 😊",
    notificationTapShortcut: "下のショートカットをタップしてノートや気分をすぐに記録できます。",
    write: "書く",
    voiceRecord: "録音",
    mood: "気分",
    advisor: "相談員",
    task: "タスク",
    photo: "写真",
    greetingTitle: "ようこそ、良い一日を ☕",
    greetingDesc: "今日は新しい成長と自分と向き合う日です。素直な思いを書き留めることが明日の力になります。",
    fullCalendar: "フルカレンダー & 1日表示 📅",
    fullCalendarSub: "日記、本、アクティビティ - クリックして任意の日の記録を確認",
    directUploadTitle: "ファイル直接アクセス & 添付 ⚡",
    attachPhoto: "写真を添付",
    attachPhotoSub: "ライブラリから",
    freeWrite: "自由記述",
    freeWriteSub: "新規エディタを開く",
    audioFile: "音声ファイル",
    audioFileSub: "録音または音声",
    phoneVideo: "動画",
    phoneVideoSub: "動画クリップをアップロード",
    aiAdvisor: "AI 相談員",
    aiAdvisorSub: "即時分析 & アドバイス",
    bookDoc: "本 / ドキュメント",
    bookDocSub: "PDFまたはテキスト",
    streakTitle: "日記継続ストリーク",
    dayStreak: "日連続",
    streakEncouragement: "素晴らしい！今日も日記を記録して継続をキープしました ✨",
    longestStreak: "過去最高ストリーク",
    recentWeek: "今週の進捗",
    selectDateTitle: "記録または表示する日付を選択:",
    quoteTitle: "今日の格言 & モチベーション 🌿",
    aiInspirationBtn: "(AI) スマートインスピレーション 🪄",
    dhikrTitle: "マインドフルネス & 瞑想 🌿",
    dhikrSub: "感謝と静けさ、心のリフレッシュの時間を取りましょう ❤️",
    dhikrCounterBtn: "カウントと瞑想はこちらをタップ 🪙",
    dhikrCountLabel: "カウンター:",
    dhikrFooter: "カウントは常に保存されます。",
    moodScaleTitle: "クイックデジタル気分スケール (1 - 10) 😐",
    moodScaleDesc: "スライダーを引いて1秒で気分を記録。AI分析に反映されます。",
    moodRating: "気分の評価:",
    waterTrackerTitle: "毎日の給水カウンター 💧",
    waterTrackerDesc: "グラスをタップして飲水量を記録。水分補給は神経を落ち着かせます。",
    waterConsumed: "摂取量:",
    waterRemaining: "理想の目標まであと数杯です 💡",
    symptomsTitle: "身体症状トラッカー ⚡",
    symptomsDesc: "今日感じた身体症状をチェックして、心身の関連性をAIで分析しましょう。",
    symptomRapidHeart: "動悸 / 頻脈 💓",
    symptomHeadache: "頭痛 / 圧迫感 🤯",
    symptomShortnessBreath: "息苦しさ 🫁",
    symptomBackTension: "筋肉痛 / 背中の痛み 🧘",
    symptomFatigue: "倦怠感 / 疲労 🔋",
    symptomPoorSleep: "不眠 / 睡眠不足 😴",
    symptomStomach: "胃の不快感 🤢",
    symptomTremors: "発汗 / 手足の震え 🥶",
    breathingTitle: "ボックスブリージングリラックス 🧘‍♂️",
    breathingDesc: "心拍数を落ち着かせる科学的に実証された呼吸法（各フェーズ4秒）",
    startBreathingBtn: "呼吸エクササイズを開始 ▶️",
    selfCareTitle: "セルフケア & メンタルヘルス目標 📝",
    sleepHours: "睡眠時間 🌙",
    workoutMinutes: "運動 / スポーツ 🏃",
    medicationDose: "薬 / ビタミン 💊",
    habitTitle: "習慣 & ルーティントラッカー 🎯",
    habitSub: "日付を選択して達成した習慣をチェックします。",
    addHabitBtn: "習慣を追加 +",
    reportTitle: "AI 行動評価レポート 📊",
    reportDesc: "期間を選択してAIによる行動分析レポートを作成します。",
    generateReportBtn: "AI 行動レポートを生成 🧠",
    lifeMapTitle: "ライフマップ & 健康指標 📊",
    lifeMapSub: "習慣とメンタルヘルスを結ぶ総合ダッシュボード。",
    balanceIndex: "毎日の健康バランス指数:",
    excellentBalance: "優れたバランス",
    sleepQuality: "睡眠の質 🌙",
    exerciseActivity: "運動と活動 🏃",
    medicationCompliance: "服薬達成 💊",
    subHabits: "習慣達成度 🎯",
    timelineTitle: "タイムライン & 本日のステップ:",
    tipTitle: "今日のメンタルヘルスのアドバイス 💡",
    tipText: "ストレスを感じた時は、1分間のボックスブリージング（吸う4秒、止める4秒、吐く4秒、止める4秒）で自律神経を整えましょう。",
  },
};

export function getTranslation(code: AppLanguage): TranslationSet {
  return MULTI_TRANSLATIONS[code] || MULTI_TRANSLATIONS['en'] || MULTI_TRANSLATIONS['ar'];
}
