import { AppLanguage } from '../types';

export interface LanguageInfo {
  code: AppLanguage;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'rtl' | 'ltr';
  speechLang: string;
  aiPromptLang: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    flag: '🇸🇦',
    dir: 'rtl',
    speechLang: 'ar-SA',
    aiPromptLang: 'Arabic (العربية)',
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    dir: 'ltr',
    speechLang: 'en-US',
    aiPromptLang: 'English',
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    dir: 'ltr',
    speechLang: 'fr-FR',
    aiPromptLang: 'French (Français)',
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    dir: 'ltr',
    speechLang: 'de-DE',
    aiPromptLang: 'German (Deutsch)',
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    dir: 'ltr',
    speechLang: 'es-ES',
    aiPromptLang: 'Spanish (Español)',
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    dir: 'ltr',
    speechLang: 'tr-TR',
    aiPromptLang: 'Turkish (Türkçe)',
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    flag: '🇵🇰',
    dir: 'rtl',
    speechLang: 'ur-PK',
    aiPromptLang: 'Urdu (اردو)',
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    dir: 'ltr',
    speechLang: 'ru-RU',
    aiPromptLang: 'Russian (Русский)',
  },
  {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文 (简体)',
    flag: '🇨🇳',
    dir: 'ltr',
    speechLang: 'zh-CN',
    aiPromptLang: 'Chinese Simplified (中文)',
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    dir: 'ltr',
    speechLang: 'ja-JP',
    aiPromptLang: 'Japanese (日本語)',
  },
];

export function getLanguageInfo(code: AppLanguage): LanguageInfo {
  return SUPPORTED_LANGUAGES.find((l) => l.code === code) || SUPPORTED_LANGUAGES[0];
}

export interface TranslationSet {
  appName: string;
  settingsTitle: string;
  settingsSubtitle: string;
  apiKeyTitle: string;
  floatingBallTitle: string;
  backupTitle: string;
  appLockTitle: string;
  favoritesTitle: string;
  remindersTitle: string;
  archiveTitle: string;
  trashTitle: string;
  darkModeTitle: string;
  notificationsTitle: string;
  languagesTitle: string;
  rateTitle: string;
  contactTitle: string;
  homeTab: string;
  diariesTab: string;
  advisorTab: string;
  analyticsTab: string;
  settingsTab: string;
  apiKeySub: string;
  apiKeySubAuto: string;
  floatingBallSub: string;
  backupSub: string;
  appLockSub: string;
  favoritesSub: string;
  remindersSub: string;
  archiveSub: string;
  trashSub: string;
  darkModeSub: string;
  notificationsSub: string;
  languagesSub: string;
  rateSub: string;
  contactSub: string;
  selectLanguageTitle: string;
  selectLanguageSubtitle: string;
  confirmLanguage: string;
  welcomeModalTitle: string;
  welcomeModalDesc: string;
}

export const MULTI_TRANSLATIONS: Record<AppLanguage, TranslationSet> = {
  ar: {
    appName: "يومياتي AI",
    settingsTitle: "الإعدادات العامة",
    settingsSubtitle: "تخصيص مساعد الذكي، قفل الحماية، وتزامن بياناتك",
    apiKeyTitle: "مفتاح API الخاص بك 🔑",
    floatingBallTitle: "عرض الكرة العائمة 🔘",
    backupTitle: "النسخ الاحتياطي والمزامنة ☁️",
    appLockTitle: "قفل التطبيق 🔐",
    favoritesTitle: "الملاحظات المفضلة ⭐",
    remindersTitle: "التذكيرات والمنبهات ⏰",
    archiveTitle: "أرشيف اليوميات 📥",
    trashTitle: "سلة المهملات 🗑️",
    darkModeTitle: "الوضع الداكن ☀️/🌙",
    notificationsTitle: "الإشعارات 🔔",
    languagesTitle: "لغات التطبيق 🌐",
    rateTitle: "قيمنا 👍",
    contactTitle: "تواصل مع مالك التطبيق للاقتراح والتطوير ✉️",
    homeTab: "الرئيسية",
    diariesTab: "اليوميات",
    advisorTab: "المستشار",
    analyticsTab: "التقدم والبيانات",
    settingsTab: "الإعدادات",
    apiKeySub: "حالة المفتاح: مخصّص ونشط محلياً 🟢",
    apiKeySubAuto: "حالة المفتاح: يتم التوفير سحابياً تلقائياً وبأمان ☁️",
    floatingBallSub: "تسهيل التنقل والتحكم السريع بالمساعد الذكي في أي وقت",
    backupSub: "حفظ ومزامنة مذكراتك سحابياً ومحلياً لمنع فقدان البيانات",
    appLockSub: "تأمين مذكراتك برمز مرور PIN مكوّن من 4 أرقام عند بدء التشغيل",
    favoritesSub: "تصفح والوصول السريع للمذكرات الأكثر أهمية (ذات 4 نجوم فما فوق)",
    remindersSub: "إدارة منبهات المهام المجدولة واليوميات",
    archiveSub: "استعراض مذكراتك المؤرشفة والقديمة",
    trashSub: "استعادة مذكراتك المحذوفة مؤخراً أو تصفيتها",
    darkModeSub: "تفعيل مظهر الوضع الليلي لحماية عينيك",
    notificationsSub: "تلقي تنبيهات دورية للعادات والتذكيرات اليومية",
    languagesSub: "تغيير لغة واجهة مستخدم التطبيق",
    rateSub: "ساعدنا على مواصلة تحسين التطبيق لرأيك الغالي",
    contactSub: "راسلنا باقتراحاتك وملاحظاتك القيمة لتطوير التطبيق",
    selectLanguageTitle: "اختر لغتك المفضل 🌐",
    selectLanguageSubtitle: "اختر لغة الواجهة والذكاء الاصطناعي المفضلة لديك للبدء",
    confirmLanguage: "متابعة بهذه اللغة 🚀",
    welcomeModalTitle: "مرحباً بك في يومياتي AI 👋",
    welcomeModalDesc: "يرجى اختيار لغتك المفضلة لاستخدام التطبيق والمساعد الذكي والتحويل الصوتي بها بكفاءة كاملة.",
  },
  en: {
    appName: "My Diaries AI",
    settingsTitle: "General Settings",
    settingsSubtitle: "Customize your smart assistant, privacy lock, and sync your data",
    apiKeyTitle: "Your API Key 🔑",
    floatingBallTitle: "Display Floating Ball 🔘",
    backupTitle: "Backup & Sync ☁️",
    appLockTitle: "App Lock 🔐",
    favoritesTitle: "Favorite Notes ⭐",
    remindersTitle: "Reminders & Alarms ⏰",
    archiveTitle: "Diary Archive 📥",
    trashTitle: "Trash Can 🗑️",
    darkModeTitle: "Dark Mode ☀️/🌙",
    notificationsTitle: "Notifications 🔔",
    languagesTitle: "App Languages 🌐",
    rateTitle: "Rate Us 👍",
    contactTitle: "Contact App Owner ✉️",
    homeTab: "Home",
    diariesTab: "Diaries",
    advisorTab: "Advisor",
    analyticsTab: "Analytics",
    settingsTab: "Settings",
    apiKeySub: "Key status: Customized & active locally 🟢",
    apiKeySubAuto: "Key status: Provided securely via cloud automatically ☁️",
    floatingBallSub: "Quick navigation and shortcut controls for your AI assistant",
    backupSub: "Sync and backup your diaries locally & to cloud securely",
    appLockSub: "Secure your notes with a 4-digit PIN lock on launch",
    favoritesSub: "Browse and quickly access your most important diaries (4+ stars)",
    remindersSub: "Manage scheduled task alarms and diary reminders",
    archiveSub: "Browse archived and older diary notes",
    trashSub: "Restore recently deleted diaries or filter them",
    darkModeSub: "Enable dark mode appearance to protect your eyes",
    notificationsSub: "Receive periodic alerts for habits and daily reminders",
    languagesSub: "Change the application user interface language",
    rateSub: "Help us continue improving the application with your feedback",
    contactSub: "Send us your valuable suggestions and notes to develop the app",
    selectLanguageTitle: "Choose Your Language 🌐",
    selectLanguageSubtitle: "Select your preferred language for the UI, voice recognition, and AI assistant",
    confirmLanguage: "Continue in this language 🚀",
    welcomeModalTitle: "Welcome to My Diaries AI 👋",
    welcomeModalDesc: "Please select your preferred language to customize the app, voice recognition, and AI assistant.",
  },
  fr: {
    appName: "Mes Journaux IA",
    settingsTitle: "Paramètres généraux",
    settingsSubtitle: "Personnalisez votre assistant intelligent, verrouillez vos données et synchronisez",
    apiKeyTitle: "Votre clé API 🔑",
    floatingBallTitle: "Bouton flottant 🔘",
    backupTitle: "Sauvegarde & Synchro ☁️",
    appLockTitle: "Verrouillage de l'application 🔐",
    favoritesTitle: "Notes favorites ⭐",
    remindersTitle: "Rappels & Alarmes ⏰",
    archiveTitle: "Archives des journaux 📥",
    trashTitle: "Corbeille 🗑️",
    darkModeTitle: "Mode Sombre ☀️/🌙",
    notificationsTitle: "Notifications 🔔",
    languagesTitle: "Langues de l'application 🌐",
    rateTitle: "Évaluez-nous 👍",
    contactTitle: "Contacter le propriétaire ✉️",
    homeTab: "Accueil",
    diariesTab: "Journaux",
    advisorTab: "Conseiller",
    analyticsTab: "Statistiques",
    settingsTab: "Paramètres",
    apiKeySub: "Statut clé: Personnalisée & active localement 🟢",
    apiKeySubAuto: "Statut clé: Fournie automatiquement par le cloud ☁️",
    floatingBallSub: "Accès rapide aux raccourcis de l'assistant IA",
    backupSub: "Sauvegardez vos journaux localement et sur le cloud",
    appLockSub: "Protégez vos notes avec un code PIN à 4 chiffres",
    favoritesSub: "Parcourez vos journaux les plus importants (4+ étoiles)",
    remindersSub: "Gérez les alarmes de tâches et rappels de journal",
    archiveSub: "Consultez vos anciens journaux archivés",
    trashSub: "Restaurez vos journaux supprimés récemment",
    darkModeSub: "Activez le mode sombre pour protéger vos yeux",
    notificationsSub: "Recevez des alertes régulières pour vos habitudes",
    languagesSub: "Changer la langue de l'interface utilisateur",
    rateSub: "Aidez-nous à améliorer l'application avec vos avis",
    contactSub: "Envoyez-nous vos suggestions pour faire évoluer l'app",
    selectLanguageTitle: "Choisissez votre langue 🌐",
    selectLanguageSubtitle: "Sélectionnez votre langue pour l'interface, la reconnaissance vocale et l'IA",
    confirmLanguage: "Continuer dans cette langue 🚀",
    welcomeModalTitle: "Bienvenue sur Mes Journaux IA 👋",
    welcomeModalDesc: "Veuillez sélectionner votre langue préférée pour personnaliser l'application et l'assistant IA.",
  },
  de: {
    appName: "Meine Tagebücher AI",
    settingsTitle: "Allgemeine Einstellungen",
    settingsSubtitle: "Passen Sie Ihren KI-Assistenten, PIN-Sperre und Synchronisierung an",
    apiKeyTitle: "Ihr API-Schlüssel 🔑",
    floatingBallTitle: "Schwebender Button 🔘",
    backupTitle: "Sicherung & Synchro ☁️",
    appLockTitle: "App-Sperre 🔐",
    favoritesTitle: "Favoriten ⭐",
    remindersTitle: "Erinnerungen & Alarme ⏰",
    archiveTitle: "Tagebuch-Archiv 📥",
    trashTitle: "Papierkorb 🗑️",
    darkModeTitle: "Dunkelmodus ☀️/🌙",
    notificationsTitle: "Benachrichtigungen 🔔",
    languagesTitle: "App-Sprachen 🌐",
    rateTitle: "Bewerten Sie uns 👍",
    contactTitle: "Entwickler kontaktieren ✉️",
    homeTab: "Startseite",
    diariesTab: "Tagebücher",
    advisorTab: "Berater",
    analyticsTab: "Analysen",
    settingsTab: "Einstellungen",
    apiKeySub: "Schlüsselstatus: Lokal aktiv 🟢",
    apiKeySubAuto: "Schlüsselstatus: Sicher über die Cloud bereitgestellt ☁️",
    floatingBallSub: "Schnellzugriff auf KI-Assistenten-Funktionen",
    backupSub: "Sichern Sie Ihre Tagebücher lokal und in der Cloud",
    appLockSub: "Sichern Sie Ihre Notizen mit einer 4-stelligen PIN",
    favoritesSub: "Durchsuchen Sie Ihre wichtigsten Tagebücher (4+ Sterne)",
    remindersSub: "Verwalten Sie Aufgabenerinnerungen und Wecker",
    archiveSub: "Durchsuchen Sie archivierte Einträge",
    trashSub: "Stellen Sie gelöschte Einträge wieder her",
    darkModeSub: "Aktivieren Sie den Dunkelmodus für Ihre Augen",
    notificationsSub: "Erhalten Sie regelmäßige Erinnerungen",
    languagesSub: "Ändern Sie die Sprache der Benutzeroberfläche",
    rateSub: "Helfen Sie uns, die App weiter zu verbessern",
    contactSub: "Senden Sie uns Ihre wertvollen Vorschläge",
    selectLanguageTitle: "Wählen Sie Ihre Sprache 🌐",
    selectLanguageSubtitle: "Wählen Sie Ihre bevorzugte Sprache für Benutzeroberfläche und KI-Assistenten",
    confirmLanguage: "In dieser Sprache fortfahren 🚀",
    welcomeModalTitle: "Willkommen bei Meine Tagebücher AI 👋",
    welcomeModalDesc: "Bitte wählen Sie Ihre bevorzugte Sprache zur Personalisierung der App.",
  },
  es: {
    appName: "Mis Diarios IA",
    settingsTitle: "Ajustes Generales",
    settingsSubtitle: "Personaliza tu asistente inteligente, bloqueo de privacidad y sincronización",
    apiKeyTitle: "Tu clave API 🔑",
    floatingBallTitle: "Botón Flotante 🔘",
    backupTitle: "Copia de Seguridad y Sincronización ☁️",
    appLockTitle: "Bloqueo de Aplicación 🔐",
    favoritesTitle: "Notas Favoritas ⭐",
    remindersTitle: "Recordatorios y Alarmas ⏰",
    archiveTitle: "Archivo de Diarios 📥",
    trashTitle: "Papelera 🗑️",
    darkModeTitle: "Modo Oscuro ☀️/🌙",
    notificationsTitle: "Notificaciones 🔔",
    languagesTitle: "Idiomas de la App 🌐",
    rateTitle: "Valóranos 👍",
    contactTitle: "Contactar con el creador ✉️",
    homeTab: "Inicio",
    diariesTab: "Diarios",
    advisorTab: "Asesor",
    analyticsTab: "Estadísticas",
    settingsTab: "Ajustes",
    apiKeySub: "Estado de clave: Personalizada y activa localmente 🟢",
    apiKeySubAuto: "Estado de clave: Provista de forma segura por la nube ☁️",
    floatingBallSub: "Atajos rápidos y navegación para tu asistente de IA",
    backupSub: "Sincroniza y guarda tus diarios de forma segura",
    appLockSub: "Protege tus notas con un código PIN de 4 dígitos",
    favoritesSub: "Accede a tus diarios más importantes (4+ estrellas)",
    remindersSub: "Gestiona las alarmas de tareas y recordatorios diario",
    archiveSub: "Explora diarios archivados y antiguos",
    trashSub: "Restaura diarios eliminados recientemente",
    darkModeSub: "Activa el modo oscuro para proteger tus ojos",
    notificationsSub: "Recibe alertas periódicas para tus hábitos",
    languagesSub: "Cambiar el idioma de la interfaz",
    rateSub: "Ayúdanos a mejorar la aplicación con tu opinión",
    contactSub: "Envíanos tus valiosas sugerencias para mejorar",
    selectLanguageTitle: "Elige tu idioma 🌐",
    selectLanguageSubtitle: "Selecciona tu idioma preferido para la app, reconocimiento de voz e IA",
    confirmLanguage: "Continuar en este idioma 🚀",
    welcomeModalTitle: "Bienvenido a Mis Diarios IA 👋",
    welcomeModalDesc: "Selecciona tu idioma preferido para personalizar la app y el asistente de IA.",
  },
  tr: {
    appName: "Günlüğüm AI",
    settingsTitle: "Genel Ayarlar",
    settingsSubtitle: "Akıllı asistanınızı, PIN kilidinizi ve veri senkronizasyonunu özelleştirin",
    apiKeyTitle: "API Anahtarınız 🔑",
    floatingBallTitle: "Yüzen Düğmeyi Göster 🔘",
    backupTitle: "Yedekleme ve Senkronizasyon ☁️",
    appLockTitle: "Uygulama Kilidi 🔐",
    favoritesTitle: "Favori Notlar ⭐",
    remindersTitle: "Hatırlatıcılar ve Alarmlar ⏰",
    archiveTitle: "Günlük Arşivi 📥",
    trashTitle: "Çöp Kutusu 🗑️",
    darkModeTitle: "Karanlık Mod ☀️/🌙",
    notificationsTitle: "Bildirimler 🔔",
    languagesTitle: "Uygulama Dilleri 🌐",
    rateTitle: "Bizi Değerlendirin 👍",
    contactTitle: "Geliştirici ile İletişim ✉️",
    homeTab: "Ana Sayfa",
    diariesTab: "Günlükler",
    advisorTab: "Danışman",
    analyticsTab: "Analizler",
    settingsTab: "Ayarlar",
    apiKeySub: "Anahtar durumu: Özel & yerel olarak aktif 🟢",
    apiKeySubAuto: "Anahtar durumu: Bulut tarafından güvenle sağlandı ☁️",
    floatingBallSub: "Yapay zeka asistanı için hızlı navigasyon kısayolları",
    backupSub: "Günlüklerinizi yerel ve bulutta güvenle yedekleyin",
    appLockSub: "Notlarınızı 4 haneli PIN koduyla koruyun",
    favoritesSub: "En önemli günlüklerinize hızla erişin (4+ yıldız)",
    remindersSub: "Zamanlanmış görev alarmlarınızı yönetin",
    archiveSub: "Arşivlenmiş eski günlüklerinize göz atın",
    trashSub: "Son silinen günlüklerinizi geri yükleyin",
    darkModeSub: "Gözlerinizi korumak için karanlık modu açın",
    notificationsSub: "Alışkanlıklar için düzenli bildirimler alın",
    languagesSub: "Uygulama arayüz dilini değiştirin",
    rateSub: "Geri bildiriminizle uygulamayı geliştirmemize yardımcı olun",
    contactSub: "Değerli önerilerinizi bize iletin",
    selectLanguageTitle: "Dilinizi Seçin 🌐",
    selectLanguageSubtitle: "Uygulama arayüzü, ses tanıma ve AI asistanı için dilinizi seçin",
    confirmLanguage: "Bu dilde devam et 🚀",
    welcomeModalTitle: "Günlüğüm AI'ya Hoş Geldiniz 👋",
    welcomeModalDesc: "Uygulama ve yapay zeka asistanını kişiselleştirmek için lütfen dilinizi seçin.",
  },
  ur: {
    appName: "میری ڈائری AI",
    settingsTitle: "عمومی ترتیبات",
    settingsSubtitle: "اپنے ذہین اسسٹنٹ، سیکیورٹی لاک، اور ڈیٹا سنک کو حسب ضرورت بنائیں",
    apiKeyTitle: "آپ کی API کی 🔑",
    floatingBallTitle: "فلوٹنگ بٹن 🔘",
    backupTitle: "بیک اپ اور سنکرونائزیشن ☁️",
    appLockTitle: "ایپ لاک 🔐",
    favoritesTitle: "پسندیدہ نوٹس ⭐",
    remindersTitle: "تذکیرات اور الارم ⏰",
    archiveTitle: "ڈائری آرکائیو 📥",
    trashTitle: "ری سائیکل بن 🗑️",
    darkModeTitle: "ڈارک موڈ ☀️/🌙",
    notificationsTitle: "نوٹیفیکیشنز 🔔",
    languagesTitle: "ایپ کی زبانیں 🌐",
    rateTitle: "ہمیں ریٹ کریں 👍",
    contactTitle: "ڈویلپر سے رابطہ کریں ✉️",
    homeTab: "ہوم",
    diariesTab: "ڈائریز",
    advisorTab: "مشیر AI",
    analyticsTab: "تجزیات",
    settingsTab: "ترتیبات",
    apiKeySub: "کی سٹیٹس: لوکل ایکٹیو 🟢",
    apiKeySubAuto: "کی سٹیٹس: کلاؤڈ کے ذریعے محفوظ خودکار ☁️",
    floatingBallSub: "AI اسسٹنٹ کے لیے تیز رفتار نیویگیشن شارٹ کٹس",
    backupSub: "اپنی ڈائریوں کو لوکل اور کلاؤڈ پر محفوظ کریں",
    appLockSub: "4 ہندسوں والے PIN کے ساتھ اپنے نوٹس محفوظ کریں",
    favoritesSub: "اپنی اہم ترین ڈائریوں تک فوری رسائی (4+ اسٹارز)",
    remindersSub: "شیڈول شدہ کاموں اور الٹیرٹس کا نظم کریں",
    archiveSub: "پرانی اور محفوظ شدہ ڈائریوں کو دیکھیں",
    trashSub: "حالیہ حذف شدہ ڈائریوں کو بحال کریں",
    darkModeSub: "آنکھوں کی حفاظت کے لیے ڈارک موڈ فعال کریں",
    notificationsSub: "عادات کے لیے باقاعدہ نوٹیفیکیشنز حاصل کریں",
    languagesSub: "ایپلی کیشن کا انٹرفیس تبدیل کریں",
    rateSub: "ایپ کو مزید بہتر بنانے میں ہماری مدد کریں",
    contactSub: "اپنی قیمتی تجاویز اور آراء بھیجیں",
    selectLanguageTitle: "اپنی زبان منتخب کریں 🌐",
    selectLanguageSubtitle: "ایپ انٹرفیس، آواز کی شناخت اور AI مشیر کے لیے زبان کا انتخاب کریں",
    confirmLanguage: "اس زبان میں جاری رکھیں 🚀",
    welcomeModalTitle: "میری ڈائری AI میں خوش آمدید 👋",
    welcomeModalDesc: "برائے مہربانی اپنی پسندیدہ زبان منتخب کریں تا کہ ایپ اور AI اسسٹنٹ آپ کی زبان میں کام کر سکے۔",
  },
  ru: {
    appName: "Мой Дневник AI",
    settingsTitle: "Общие настройки",
    settingsSubtitle: "Настройте умного ассистента, PIN-код и синхронизацию данных",
    apiKeyTitle: "Ваш API-ключ 🔑",
    floatingBallTitle: "Плавающая кнопка 🔘",
    backupTitle: "Резервное копирование и синхронизация ☁️",
    appLockTitle: "Блокировка приложения 🔐",
    favoritesTitle: "Избранные заметки ⭐",
    remindersTitle: "Напоминания и будильники ⏰",
    archiveTitle: "Архив дневников 📥",
    trashTitle: "Корзина 🗑️",
    darkModeTitle: "Тёмная тема ☀️/🌙",
    notificationsTitle: "Уведомления 🔔",
    languagesTitle: "Языки приложения 🌐",
    rateTitle: "Оцените нас 👍",
    contactTitle: "Связаться с разработчиком ✉️",
    homeTab: "Главная",
    diariesTab: "Дневники",
    advisorTab: "Советник",
    analyticsTab: "Аналитика",
    settingsTab: "Настройки",
    apiKeySub: "Статус ключа: Настроен и активен локально 🟢",
    apiKeySubAuto: "Статус ключа: Безопасно предоставляется облаком ☁️",
    floatingBallSub: "Быстрый доступ к функциям ИИ-ассистента",
    backupSub: "Синхронизируйте и сохраняйте записи в облаке",
    appLockSub: "Защитите записи 4-значным PIN-кодом",
    favoritesSub: "Быстрый доступ к самым важным записям (4+ звезды)",
    remindersSub: "Управление напоминаниями и задачами",
    archiveSub: "Просмотр архивных и старых записей",
    trashSub: "Восстановление недавно удаленных записей",
    darkModeSub: "Включите тёмную тему для защиты глаз",
    notificationsSub: "Получайте регулярные напоминания о привычках",
    languagesSub: "Изменить язык интерфейса приложения",
    rateSub: "Помогите нам улучшить приложение вашим отзывом",
    contactSub: "Отправьте нам ваши ценные предложения",
    selectLanguageTitle: "Выберите ваш язык 🌐",
    selectLanguageSubtitle: "Выберите язык интерфейса, распознавания речи и ИИ-ассистента",
    confirmLanguage: "Продолжить на этом языке 🚀",
    welcomeModalTitle: "Добро пожаловать в Мой Дневник AI 👋",
    welcomeModalDesc: "Пожалуйста, выберите предпочитаемый язык для персонализации приложения и ИИ.",
  },
  zh: {
    appName: "我的日记 AI",
    settingsTitle: "通用设置",
    settingsSubtitle: "自定义您的智能助手、密码锁和数据同步",
    apiKeyTitle: "您的 API 密钥 🔑",
    floatingBallTitle: "显示悬浮球 🔘",
    backupTitle: "备份与同步 ☁️",
    appLockTitle: "应用锁 🔐",
    favoritesTitle: "收藏笔记 ⭐",
    remindersTitle: "提醒与闹钟 ⏰",
    archiveTitle: "日记归档 📥",
    trashTitle: "回收站 🗑️",
    darkModeTitle: "深色模式 ☀️/🌙",
    notificationsTitle: "通知 🔔",
    languagesTitle: "应用语言 🌐",
    rateTitle: "评价我们 👍",
    contactTitle: "联系开发者 ✉️",
    homeTab: "首页",
    diariesTab: "日记",
    advisorTab: "AI顾问",
    analyticsTab: "数据分析",
    settingsTab: "设置",
    apiKeySub: "密钥状态：自定义并在本地激活 🟢",
    apiKeySubAuto: "密钥状态：由云端安全自动提供 ☁️",
    floatingBallSub: "快捷导航与AI助手控制",
    backupSub: "安全备份您的日记到本地和云端",
    appLockSub: "使用 4 位 PIN 码保护您的隐私",
    favoritesSub: "快速浏览最重要的日记（4星及以上）",
    remindersSub: "管理日程提醒与日常任务",
    archiveSub: "浏览已归档的旧日记",
    trashSub: "恢复最近删除的日记",
    darkModeSub: "开启深色模式保护眼睛",
    notificationsSub: "接收习惯与日记的定期提醒",
    languagesSub: "更改应用程序界面语言",
    rateSub: "提出宝贵意见，帮助我们做得更好",
    contactSub: "向我们发送您的建议与反馈",
    selectLanguageTitle: "选择您的语言 🌐",
    selectLanguageSubtitle: "选择界面、语音识别和 AI 助手的偏好语言",
    confirmLanguage: "使用此语言继续 🚀",
    welcomeModalTitle: "欢迎使用 我的日记 AI 👋",
    welcomeModalDesc: "请选择您的偏好语言以个性化应用和 AI 助手。",
  },
  ja: {
    appName: "マイ AI 日記",
    settingsTitle: "一般設定",
    settingsSubtitle: "AI アシスタント、パスコードロック、同期のカスタマイズ",
    apiKeyTitle: "API キー 🔑",
    floatingBallTitle: "フローティングボタン表示 🔘",
    backupTitle: "バックアップと同期 ☁️",
    appLockTitle: "アプリロック 🔐",
    favoritesTitle: "お気に入りノート ⭐",
    remindersTitle: "リマインダーとアラーム ⏰",
    archiveTitle: "日記アーカイブ 📥",
    trashTitle: "ゴミ箱 🗑️",
    darkModeTitle: "ダークモード ☀️/🌙",
    notificationsTitle: "通知 🔔",
    languagesTitle: "アプリの言語 🌐",
    rateTitle: "アプリを評価 👍",
    contactTitle: "開発者に連絡 ✉️",
    homeTab: "ホーム",
    diariesTab: "日記",
    advisorTab: "AI相談員",
    analyticsTab: "分析",
    settingsTab: "設定",
    apiKeySub: "キー状態: カスタム & ローカルでアクティブ 🟢",
    apiKeySubAuto: "キー状態: クラウド経由で自動供給 ☁️",
    floatingBallSub: "AIアシスタントへのクイックアクセスショートカット",
    backupSub: "日記をローカルおよびクラウドに安全にバックアップ",
    appLockSub: "4桁のPINコードでノートを保護",
    favoritesSub: "最も重要な日記にクイックアクセス（星4以上）",
    remindersSub: "スケジュールされたタスクのアラームを管理",
    archiveSub: "アーカイブされた古い日記を閲覧",
    trashSub: "最近削除した日記を復元",
    darkModeSub: "目に優しいダークモードを有効化",
    notificationsSub: "習慣のリマインダー通知を受け取る",
    languagesSub: "アプリのユーザーインターフェース言語を変更",
    rateSub: "フィードバックでアプリの改善にご協力ください",
    contactSub: "開発者にご意見・ご要望を送信",
    selectLanguageTitle: "言語を選択してください 🌐",
    selectLanguageSubtitle: "UI、音声認識、AIアシスタントの言語を選択します",
    confirmLanguage: "この言語で続ける 🚀",
    welcomeModalTitle: "マイ AI 日記へようこそ 👋",
    welcomeModalDesc: "アプリやAIアシスタントを最適化するため、お好みの言語を選択してください。",
  },
};
